### ISSUE TITLE
CUDA sqrt() for double precision number

### ISSUE THREAD

**Issue by maranGit** [taichi-dev/taichi#2572] opened 2021-07-22 16:16 UTC
**Describe the bug**
In CUDA, sqrt() function only produces results with single-digit precision, while other functions like exp() and log() produce correct results with double-digit precision.

**To Reproduce**

```py
import taichi as ti
# ti.init(arch=ti.cpu, default_ip=ti.i32, default_fp=ti.f64)
ti.init(arch=ti.cuda, default_ip=ti.i32, default_fp=ti.f64)
@ti.kernel
def test():
  aa = 2.0101010101010101010101
  print(ti.sqrt(aa))
test()
```

**Log/Screenshots**

```
$ python3 my_sample_code.py
[Taichi] mode=release
[Taichi] preparing sandbox at /tmp/taichi-4w7qkp6q
[Taichi] version 0.7.20, llvm 10.0.0, commit 284f75ed, linux, python 3.8.5
[Taichi] Starting on arch=cuda
[Taichi] materializing...
1.417780876160
```

**Comment by k-ye** [comment] 2021-07-23 01:17
Thank! @strongoier could you help take a look?

**Comment by strongoier** [comment] 2021-07-23 02:19
> Thank! @strongoier could you help take a look?

Sure

**Comment by victoriacity** [comment] 2021-07-23 03:54
Adding `fast_math=False` to `ti.init` seems to solve the problem.

**Comment by strongoier** [comment] 2021-07-23 04:07
> Adding `fast_math=False` to `ti.init` seems to solve the problem.
> 
> As in
> 
> https://github.com/taichi-dev/taichi/blob/7e54f56d305f370f773264864f7fcf117470ddf1/taichi/backends/cuda/jit_cuda.cpp#L201-L206
> ,
> 
> `fast_math=True` will result in slightly approximated square root values. I'm not sure if the difference in this issue is expected and the CUDA backend didn't seem problematic on generating sqrt calls.
> 
> https://github.com/taichi-dev/taichi/blob/72f2697093dcf444a55b730669a29b9f26257197/taichi/backends/cuda/codegen_cuda.cpp#L209-L216

You're right. I also confirmed the behavior by looking at the generated PTX.
With `fast_math=True` (default), the generated PTX is
```
	rsqrt.approx.f64 	%fd2, %fd1;
	rcp.approx.ftz.f64 	%fd3, %fd2;
```
, which is approximating the sqrt result.
With `fast_math=False`, the generated PTX is
```
	sqrt.rn.f64 	%fd2, %fd1;
```
, which is accurate.

**Comment by xumingkuan** [comment] 2021-07-23 08:54
Maybe we need different "levels" of `fast_math` to distinguish the cases "there should not be any INFs or NaNs so I can optimize it" and "I don't care about the precision so I can optimize it"?

**Comment by bobcao3** [comment] 2021-07-23 08:56
There are the precision decorators in GLSL / HLSL, maybe have an 'precise'
tag for arithmetics so that the backend knows which one should be used

**Comment by strongoier** [comment] 2022-10-21 06:36
I'll close this issue because the problem has been treated in #6346.

**Closed by strongoier** 2022-10-21 06:36 UTC
Labels: potential bug
