### ISSUE TITLE
Can't import taichi (from 0.5.15) using Ubuntu 20.04 in VM

### ISSUE THREAD

**Issue by TroyZhai** [taichi-dev/taichi#958] opened 2020-05-12 06:30 UTC
Taichi fail to load in Ubuntu 20.04 using VM since 0.5.15, tried with both VMware Player and VirtualBox. Version 0.5.14 and before are fine.

![image](https://user-images.githubusercontent.com/7610945/81645892-78b2df00-947e-11ea-9ccc-a3d967ba709b.png)

![image](https://user-images.githubusercontent.com/7610945/81645940-88322800-947e-11ea-84c0-90ca065d7b5f.png)

**Comment by archibate** [comment] 2020-05-12 07:19
Thank for the patient! The issue is because the recently added OpenGL backend in v0.5.15.
It's heard that VM doesn't have OpenGL driver support. Do you have the same problem on your physical machine (not in VM)?

**Comment by TroyZhai** [comment] 2020-05-12 08:10
Sure, VMs are not famous for their OpenGL compatibility. I got 3.3 on VMware but only 2.1 in VirtualBox. Sadly I don't have a proper environment on my physical machine. Could you please don't assume a gl version and make it work with CPU only, just like before? The glxinfo from VMs are attached

![image](https://user-images.githubusercontent.com/7610945/81657489-05b06500-948c-11ea-8298-973ddaf0d0de.png)

![image](https://user-images.githubusercontent.com/7610945/81658049-8a9b7e80-948c-11ea-905d-8701c053cacb.png)

**Comment by archibate** [comment] 2020-05-12 11:02
> I got 3.3 on VMware but only 2.1 in VirtualBox.

While Taichi requires 4.3 to work.
We should detect the version before calling into `glfwCreateWindow` and return false at that situation:
https://github.com/taichi-dev/taichi/blob/e0ef399b2c2f053918e1013fea9850022c96bced/taichi/backends/opengl/opengl_api.cpp#L517-L519

But the problem comes:
We need an OpenGL context to call `glGetInteger(GL_VERSION)`.
We need `glfwCreateWindow` to get an OpenGL context.
We need `glGetInteger(GL_VERSION)` to determine weather to call `glfwCreateWindow` (which may cause a segfault).

> Could you please don't assume a gl version and make it work with CPU only, just like before?

Possible temporary solution: remove line 455-456 from `~/.local/lib/python3.8/site-packages/taichi/core/util.py`:
```
    if ti_core.with_opengl():
        supported_archs.append('opengl')
```

**Comment by TroyZhai** [comment] 2020-05-12 12:17
Thanks for the reply. I know it probably requires the compute shader for OpenGL to really shine. However, having OpenGL 4.3 is almost impossible currently for most VMs at my best knowledge, so I'd like to fall back on x64 for now. 
Removing L455-456 in util.py fixes the line 'import taichi as ti', but when I do 'ti.init(arch=ti.x64)', I still get pretty much the same error. In the callstack I can still see OpenGL being initialized. I'm not quite sure what's going on behind the scene but it seems that ti_core.with_opengl() is still true even if arch=ti.x64 is passed in. 

![image](https://user-images.githubusercontent.com/7610945/81689597-8b450c80-94ae-11ea-8771-0741451b512d.png)

**Comment by archibate** [comment] 2020-05-12 13:30
Thank for the information, I found another `with_opengl` in L271-L272 from `~/.local/lib/python3.8/site-packages/taichi/lang/__init__.py`:
```py
if ti_core.with_opengl():
        archs.append(opengl)
```

> but it seems that ti_core.with_opengl() is still true even if arch=ti.x64 is passed in.

Note that `with_opengl` is no expected to return false with `arch=ti.x64` specified, it basically detects if the OpenGL driver is available, and return false only when driver unavailable, instead of a manual specifed `arch`.
However, `with_opengl` crashed into segment fault when detecting OpenGL availability...
It would be straightforward if we can **catch** that `SIGSEGV`, and return false on that condition.
python-pseudo code:
```py
def with_opengl():
   try:
      return initialize_opengl()
   except:
      return False
```
This also applies to CUDA backend, which is commonly reported to be crash (@yuanming-hu), what do you think?

---

Btw, you can run `TI_LOG_LEVEL=trace python xxx.py` to print more details about the internal process.

**Comment by k-ye** [comment] 2020-05-12 14:22
BTW, is it possible to detect OpenGL version inside `with_opengl()`, something like [this](https://stackoverflow.com/a/37657349/12003165)? Report `true` only if `version >= 4.3`?

**Comment by archibate** [comment] 2020-05-12 15:03
> BTW, is it possible to detect OpenGL version inside `with_opengl()`, something like [this](https://stackoverflow.com/a/37657349/12003165)? Report `true` only if `version >= 4.3`?

Thank for the suggestion, I hope so, but we can't call `glGetInteger` before `glfwCreateWindow`. I think we will stick to the catch-segmentation-fault approach, which is also helpful for CUDA.

> We need an OpenGL context to call glGetString(GL_VERSION).
> We need glfwCreateWindow to get an OpenGL context.
> We need glGetString(GL_VERSION) to determine weather to call glfwCreateWindow (cause segfault)

**Comment by yuanming-hu** [comment] 2020-05-12 15:54
A probably easier solution: can we simply have a `.taichiconfig` to disable OpenGL manually in certain environments?

**Comment by archibate** [comment] 2020-05-12 15:56
Yes, we can, if you mean, users without environment manually add `TI_WITH_OPENGL=0` in `.bashrc`?

**Comment by yuanming-hu** [comment] 2020-05-12 15:59
Oh, making use of environment variables does sound like a good solution for *nix users! Let's use something like `TI_ENABLE_OPENGL`?

We should also consider how to make taichi work out-of-box without setting anything like an envvar. On the other hand, we don't want to set `TI_ENABLE_OPENGL=0` by default. Do you have an idea on how to achieve both?

**Comment by TroyZhai** [comment] 2020-05-12 21:06
Thanks for all the timely replies. You guys are amazing!

**Comment by archibate** [comment] 2020-05-13 13:05
You're welcome, thank you for pointing out the bug and valuable informations!
@yuanming-hu Can we release #962 with v0.6.4 tonight? So that @TroyZhai can try out `TI_ENABLE_OPENGL=0` and see if it works.

**Comment by yuanming-hu** [comment] 2020-05-13 15:46
Sure - I have meetings in the morning but I'll release v0.6.4 in a couple of hours.

**Comment by yuanming-hu** [comment] 2020-05-13 23:16
@TroyZhai We just now released v0.6.4. When you get a chance, could you upgrade and run with `TI_ENABLE_OPENGL=0`? Please let us know if that works.

No rush on this at all. Thank you!

**Comment by TroyZhai** [comment] 2020-05-14 00:43
> @TroyZhai We just now released v0.6.4. When you get a chance, could you upgrade and run with `TI_ENABLE_OPENGL=0`? Please let us know if that works.
> 
> No rush on this at all. Thank you!

Great news! I can confirm that it works as expected on my VMs when I set "export TI_ENABLE_OPENGL=0". Thanks all!

**Comment by yuanming-hu** [comment] 2020-05-14 01:28
Awesome!

I'm closing this thanks to the hard work by @archibate.

**Closed by yuanming-hu** 2020-05-14 01:28 UTC
Labels: dependency, linux, opengl, potential bug

**Comment by archibate** [comment] 2020-05-14 01:39
Cool! But how about to add this usage to doc? Potentially a chapter called `Troubleshooting`, contains `TI_ENABLE_OPENGL` and `TI_USE_UNIFIED_MEMORY`, etc., so that these will solve more people's problem.

**Comment by yuanming-hu** [comment] 2020-05-14 01:52
Sounds good! Should we mode the following items in the README file there as well?

> - On Ubuntu 19.04+, please sudo apt install libtinfo5.
> - On Windows, please install Microsoft Visual C++ Redistributable if you haven't.

A chapter named `Installation` sounds good. We can address all compatibility issues there. Maybe we can put it before `Hello world`?

These text in `Hello world` should also be moved there:
> First of all, let’s install Taichi via pip:
> 
> ```
> # Python 3.6+ needed
> python3 -m pip install taichi
> ```
