### ISSUE TITLE
difftaichi/examples/billiards.py breaks on 1.4.0

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#7103] opened 2023-01-09 10:03 UTC
**Describe the bug**
The billiards only move in the first iteration, and then it freezes. All the losses are the same after that.

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
python billiards.py 
[Taichi] version 1.4.0, llvm 15.0.4, commit 9c6acb5f, linux, python 3.10.0
[Taichi] Starting on arch=x64
/home/lin/difftaichi/examples/billiards.py:64: DeprecationWarning: Calling builtin function "min" in Taichi scope is deprecated. Please use "ti.min" instead.
  toi = (dist_norm - 2 * radius) / min(
Iter= 0 Loss= 0.04541793838143349
Iter= 1 Loss= 0.06608898937702179
Iter= 2 Loss= 0.06608898937702179
Iter= 3 Loss= 0.06608898937702179
Iter= 4 Loss= 0.06608898937702179
Iter= 5 Loss= 0.06608898937702179
Iter= 6 Loss= 0.06608898937702179
Iter= 7 Loss= 0.06608898937702179
Iter= 8 Loss= 0.06608898937702179
Iter= 9 Loss= 0.06608898937702179
Iter= 10 Loss= 0.06608898937702179
Iter= 11 Loss= 0.06608898937702179
Iter= 12 Loss= 0.06608898937702179
Iter= 13 Loss= 0.06608898937702179
Iter= 14 Loss= 0.06608898937702179
Iter= 15 Loss= 0.06608898937702179
Iter= 16 Loss= 0.06608898937702179
Iter= 17 Loss= 0.06608898937702179
Iter= 18 Loss= 0.06608898937702179
Iter= 19 Loss= 0.06608898937702179
Iter= 20 Loss= 0.06608898937702179
Iter= 21 Loss= 0.06608898937702179
Iter= 22 Loss= 0.06608898937702179
Iter= 23 Loss= 0.06608898937702179
Iter= 24 Loss= 0.06608898937702179
Iter= 25 Loss= 0.06608898937702179
Iter= 26 Loss= 0.06608898937702179
Iter= 27 Loss= 0.06608898937702179
Iter= 28 Loss= 0.06608898937702179
Iter= 29 Loss= 0.06608898937702179
Iter= 30 Loss= 0.06608898937702179
Iter= 31 Loss= 0.06608898937702179
Iter= 32 Loss= 0.06608898937702179
Iter= 33 Loss= 0.06608898937702179
Iter= 34 Loss= 0.06608898937702179
Iter= 35 Loss= 0.06608898937702179
Iter= 36 Loss= 0.06608898937702179
Iter= 37 Loss= 0.06608898937702179
Iter= 38 Loss= 0.06608898937702179
Iter= 39 Loss= 0.06608898937702179
Iter= 40 Loss= 0.06608898937702179
Iter= 41 Loss= 0.06608898937702179
Iter= 42 Loss= 0.06608898937702179
Iter= 43 Loss= 0.06608898937702179
Iter= 44 Loss= 0.06608898937702179
Iter= 45 Loss= 0.06608898937702179
Iter= 46 Loss= 0.06608898937702179
Iter= 47 Loss= 0.06608898937702179
Iter= 48 Loss= 0.06608898937702179
Iter= 49 Loss= 0.06608898937702179
Iter= 50 Loss= 0.06608898937702179
Iter= 51 Loss= 0.06608898937702179
Iter= 52 Loss= 0.06608898937702179
Iter= 53 Loss= 0.06608898937702179
Iter= 54 Loss= 0.06608898937702179
Iter= 55 Loss= 0.06608898937702179
Iter= 56 Loss= 0.06608898937702179
Iter= 57 Loss= 0.06608898937702179
Iter= 58 Loss= 0.06608898937702179
Iter= 59 Loss= 0.06608898937702179
Iter= 60 Loss= 0.06608898937702179
Iter= 61 Loss= 0.06608898937702179
Iter= 62 Loss= 0.06608898937702179
Iter= 63 Loss= 0.06608898937702179
Iter= 64 Loss= 0.06608898937702179
Iter= 65 Loss= 0.06608898937702179
Iter= 66 Loss= 0.06608898937702179
Iter= 67 Loss= 0.06608898937702179
Iter= 68 Loss= 0.06608898937702179
Iter= 69 Loss= 0.06608898937702179
Iter= 70 Loss= 0.06608898937702179
Iter= 71 Loss= 0.06608898937702179
Iter= 72 Loss= 0.06608898937702179
Iter= 73 Loss= 0.06608898937702179
Iter= 74 Loss= 0.06608898937702179
Iter= 75 Loss= 0.06608898937702179
Iter= 76 Loss= 0.06608898937702179
Iter= 77 Loss= 0.06608898937702179
Iter= 78 Loss= 0.06608898937702179
Iter= 79 Loss= 0.06608898937702179
Iter= 80 Loss= 0.06608898937702179
Iter= 81 Loss= 0.06608898937702179
Iter= 82 Loss= 0.06608898937702179
Iter= 83 Loss= 0.06608898937702179
Iter= 84 Loss= 0.06608898937702179
Iter= 85 Loss= 0.06608898937702179
Iter= 86 Loss= 0.06608898937702179
Iter= 87 Loss= 0.06608898937702179
Iter= 88 Loss= 0.06608898937702179
Iter= 89 Loss= 0.06608898937702179
Iter= 90 Loss= 0.06608898937702179
Iter= 91 Loss= 0.06608898937702179
Iter= 92 Loss= 0.06608898937702179
Iter= 93 Loss= 0.06608898937702179
Iter= 94 Loss= 0.06608898937702179
Iter= 95 Loss= 0.06608898937702179
Iter= 96 Loss= 0.06608898937702179
Iter= 97 Loss= 0.06608898937702179
Iter= 98 Loss= 0.06608898937702179
Iter= 99 Loss= 0.06608898937702179
Iter= 100 Loss= 0.06608898937702179
Iter= 101 Loss= 0.06608898937702179
Iter= 102 Loss= 0.06608898937702179
Iter= 103 Loss= 0.06608898937702179
Iter= 104 Loss= 0.06608898937702179
Iter= 105 Loss= 0.06608898937702179
Iter= 106 Loss= 0.06608898937702179
Iter= 107 Loss= 0.06608898937702179
Iter= 108 Loss= 0.06608898937702179
Iter= 109 Loss= 0.06608898937702179
Iter= 110 Loss= 0.06608898937702179
Iter= 111 Loss= 0.06608898937702179
Iter= 112 Loss= 0.06608898937702179
Iter= 113 Loss= 0.06608898937702179
Iter= 114 Loss= 0.06608898937702179
Iter= 115 Loss= 0.06608898937702179
Iter= 116 Loss= 0.06608898937702179
Iter= 117 Loss= 0.06608898937702179
Iter= 118 Loss= 0.06608898937702179
Iter= 119 Loss= 0.06608898937702179
Iter= 120 Loss= 0.06608898937702179
Iter= 121 Loss= 0.06608898937702179
Iter= 122 Loss= 0.06608898937702179
Iter= 123 Loss= 0.06608898937702179
Iter= 124 Loss= 0.06608898937702179
Iter= 125 Loss= 0.06608898937702179
Iter= 126 Loss= 0.06608898937702179
Iter= 127 Loss= 0.06608898937702179
Iter= 128 Loss= 0.06608898937702179
Iter= 129 Loss= 0.06608898937702179
Iter= 130 Loss= 0.06608898937702179
Iter= 131 Loss= 0.06608898937702179
Iter= 132 Loss= 0.06608898937702179
Iter= 133 Loss= 0.06608898937702179
Iter= 134 Loss= 0.06608898937702179
Iter= 135 Loss= 0.06608898937702179
```

**Comment by jim19930609** [comment] 2023-01-10 03:21
Verified it's an issue with `f735fe180 [Lang] Enable real_matrix and real_matrix_scalarize by default (#6801)`. Assign to myself for further investigations

**Comment by jim19930609** [comment] 2023-01-10 03:42
Caused by `19fce81e0 [opt] Add pass eliminate_immutable_local_vars (#6926)`, investigating.

**Comment by jim19930609** [comment] 2023-01-10 10:37
Here's a minimal code to reproduce this `nan` issue: 
```
import math
import numpy as np
import os
import matplotlib.pyplot as plt 

real = ti.f32
ti.init(default_fp=real, offline_cache=False, flatten_if=True, print_ir=True)

scalar = lambda: ti.field(dtype=real)
vec = lambda: ti.Vector.field(2, dtype=real)

loss = scalar()
init_x = vec()
impulse = vec()

ti.root.place(init_x)
ti.root.place(loss)
ti.root.place(impulse)
ti.root.lazy_grad()

@ti.kernel
def collide():
    imp = ti.Vector([0.0, 0.0])
    dist = init_x[None]
    cond = dist[0] < 0.06
    if cond:
        dir = (1.0 / dist.sum()) * dist
        imp = 0.5 * dir 
        #print(1111)
    impulse[None] = imp 

init_x[None] = [0.1, 0.5]
with ti.ad.Tape(loss):
    collide()

print(init_x.grad[None][0])
print(init_x.grad[None][1])
```

**Comment by erizmr** [comment] 2023-01-10 10:46
[The #](https://github.com/taichi-dev/difftaichi/pull/64) is a temporary fix for this issue. A new issue #7115 is opened to track the repro above.

**Comment by jim19930609** [comment] 2023-01-10 10:49
lol, I also filed a similar one: https://github.com/taichi-dev/taichi/issues/7116

**Closed** 2023-01-11 00:39 UTC
