### ISSUE TITLE
[RFC] Support parameter groups

### ISSUE THREAD

**Issue by YuCrazing** [taichi-dev/taichi#6209] opened 2022-09-30 03:33 UTC
**Concisely describe the problem**
As the size of codebase gets larger,  we need spend more time to organize function parameters' passing , which is a kind of a waste of time and energy. For example, in the below snippet, we need to manually write all parameter names at every function signature and every function invoking.

```python
grid_vel = ti.Vector.ndarray(2, dtype=ti.f32, shape=(n_grid, n_grid))
grid_mass = ti.ndarray(dtype=ti.f32, shape=(n_grid, n_grid))
grid_mask = ti.ndarray(dtype=ti.i32, shape=(n_grid, n_grid))

particle_pos = ti.Vector.ndarray(2, dtype=ti.f32, shape=n_particles)
particle_vel = ti.Vector.ndarray(2, dtype=ti.f32, shape=n_particles)
particle_C = ti.Vector.ndarray(2, 2, dtype=ti.f32, shape=n_particles)
particle_material = ti.ndarray(dtype=ti.i32, shape=n_particles)

@ti.kernel
def init(
    grid_v: ti.any_arr(field_dim=2),
    grid_m: ti.any_arr(field_dim=2),
    grid_mask: ti.any_arr(field_dim=2),
    particle_pos: ti.any_arr(field_dim=1), 
    particle_vel: ti.any_arr(field_dim=1), 
    particle_C: ti.any_arr(field_dim=1), 
    particle_material: ti.any_arr(field_dim=1), 
):
    for i, j in grid_m:
        grid_v[i, j] = [0, 0]
        grid_m[i, j] = 0
        grid_mask[i, j] = 0
    for i in particle_pos:
        particle_pos[i] = ti.Vector([0.0, 0.0])

@ti.kernel
def substep(
    grid_v: ti.any_arr(field_dim=2),
    grid_m: ti.any_arr(field_dim=2),
    grid_mask: ti.any_arr(field_dim=2),
    particle_pos: ti.any_arr(field_dim=1), 
    particle_vel: ti.any_arr(field_dim=1), 
    particle_C: ti.any_arr(field_dim=1), 
    particle_material: ti.any_arr(field_dim=1), 
):
    for i, j in grid_m:
        grid_v[i, j] = [0, 0]
        grid_m[i, j] = 0
        grid_mask[i, j] = 0
    for i in particle_pos:
        particle_pos[i] += grid_vel[I]


init(grid_vel, grid_mass, grid_mask, particle_pos, particle_vel, particle_C, particle_material)

for i in range(100):
    substep(grid_vel, grid_mass, grid_mask, particle_pos, particle_vel, particle_C, particle_material)
```

**Describe the solution you'd like (if any)**
I wish there will be a `ParameterGroup` concept (on both python and c++ side) to avoid the problem mentioned above. Via `ParameterGroup`, we can group parameters as a unit to avoid manually organizing parameters:
``` python
grid_para_group = ti.ParameterGroup(grid_vel, grid_mass, grid_mask)
particle_para_group = ti.ParameterGroup(particle_pos, particle_vel, particle_C, particle_material)
```

An example of the usage of `ParameterGroup` could be:
```python


grid_vel = ti.Vector.ndarray(2, dtype=ti.f32, shape=(n_grid, n_grid))
grid_mass = ti.ndarray(dtype=ti.f32, shape=(n_grid, n_grid))
grid_mask = ti.ndarray(dtype=ti.i32, shape=(n_grid, n_grid))

particle_pos = ti.Vector.ndarray(2, dtype=ti.f32, shape=n_particles)
particle_vel = ti.Vector.ndarray(2, dtype=ti.f32, shape=n_particles)
particle_C = ti.Vector.ndarray(2, 2, dtype=ti.f32, shape=n_particles)
particle_material = ti.ndarray(dtype=ti.i32, shape=n_particles)

# Add multiple buffers into a ParameterGroup
grid_para_group = ti.ParameterGroup(grid_vel, grid_mass, grid_mask)
particle_para_group = ti.ParameterGroup(particle_pos, particle_vel, particle_C, particle_material)

@ti.kernel
def init(grid: ti.ParameterGroup, particle: ti.ParameterGroup):

    grid_v = grid.grid_vel
    grid_m = grid.grid_mass
    grid_mask = grid.grid_mask
    particl_pos = particle.particle_pos
    particl_vel = particle.particle_vel
    particl_C = particle.particle_C
    particl_material = particle.particle_material
    
    for i, j in grid_m:
        grid_v[i, j] = [0, 0]
        grid_m[i, j] = 0
        grid_mask[i, j] = 0
    for i in particle_pos:
        particle_pos[i] = ti.Vector([0.0, 0.0])

@ti.kernel
def substep(grid: ti.ParameterGroup, particle: ti.ParameterGroup):

    grid_v = grid.grid_vel
    grid_m = grid.grid_mass
    grid_mask = grid.grid_mask
    particl_pos = particle.particle_pos
    particl_vel = particle.particle_vel
    particl_C = particle.particle_C
    particl_material = particle.particle_material

    for i, j in grid_m:
        grid_v[i, j] = [0, 0]
        grid_m[i, j] = 0
        grid_mask[i, j] = 0
    for i, j in grid_m:
        grid_v[i, j] = [0, 0]
        grid_m[i, j] = 0
        grid_mask[i, j] = 0
    for i in particle_pos:
        particle_pos[i] += grid_vel[i]

init(grid_para_group, particle_para_group)
for i in range(100):
    substep(grid_para_group, particle_para_group)
```

**Comment by bobcao3** [comment] 2022-10-03 21:14
Duplicate of #5662 ?

**Comment by YuCrazing** [comment] 2022-10-08 07:21
Yeap, what I want here is a kind of basic `argpacks`. Thanks for reminding me that there is already a similar proposal. I think we can take #5662 as a reference when implementing this feature in v1.2.0 milestone. (cc @ailzhang)

**Comment by listerily** [comment] 2023-07-13 06:32
Close this issue as completed and duplicate. Basic functionalities of `argpack` are implemented and merged into master.

For future improvements on `argpack`, please refer to #5662.

**Closed by listerily** 2023-07-13 06:32 UTC
Labels: feature request
