### ISSUE TITLE
build taichi from source with cuda8.0 

### ISSUE THREAD

**Issue by jakoaltrd** [taichi-dev/taichi#2301] opened 2021-04-27 02:02 UTC
to use at my own risk, I need to build taichi from source , so I post this request

cuda 10/11 is required to build taichi from source from the developer guideline. but I need to use cuda8.0 at my own rish, so I request that taichi can work along with cuda8.0 backend.

comments: if taichi are inherently not compatiable with cuda8.0, can our developers take 
some effort to add cuda8.0 support into the backend, so that we can use lower cuda version in taichi !!

**Comment by k-ye** [comment] 2021-04-27 09:25
Hi @jakoaltrd , 

We probably don't have so much time to support older CUDA versions. If you're interested, could you post the specific errors when using CUDA 8.0 so that others can help take a look?

A kind reminder that please post the questions in one issue, so that people can have a complete context. I'm closing this because it's a duplicate of #2296

**Closed by k-ye** 2021-04-27 09:25 UTC
Labels: feature request
