### ISSUE TITLE
LLVM Fatal Error: Copy one register into another with a different width

### ISSUE THREAD

**Issue by AmesingFlank** [taichi-dev/taichi#8086] opened 2023-05-26 06:01 UTC
repro:
```py
import taichi as ti

ti.init(ti.cuda)

@ti.dataclass
class S:
    i: ti.i16 = 0
    b: bool = False

sf = S.field(shape=(10,  2))

@ti.kernel
def k() -> S:
    ss = [sf[0,0], sf[0,1]]
    return ss[0]

k()
```
this throws:
```
Traceback (most recent call last):
  File "C:\Users\ldfra\Code\taichi\test_llvm_throw.py", line 19, in <module>
    k()
  File "c:\users\ldfra\code\taichi\python\taichi\lang\kernel_impl.py", line 936, in wrapped
    return primal(*args, **kwargs)
  File "c:\users\ldfra\code\taichi\python\taichi\lang\kernel_impl.py", line 868, in __call__
    return self.launch_kernel(kernel_cpp, *args)
  File "c:\users\ldfra\code\taichi\python\taichi\lang\kernel_impl.py", line 801, in launch_kernel
    raise e from None
  File "c:\users\ldfra\code\taichi\python\taichi\lang\kernel_impl.py", line 798, in launch_kernel
    prog.launch_kernel(compiled_kernel_data, launch_ctx)
RuntimeError: [llvm_context.cpp:taichi::lang::TaichiLLVMContext::{ctor}::<lambda_ea41ae353cd42ca584262925730f46b7>::operator ()@80] LLVM Fatal Error: Copy one register into another with a different width
```
The problem looks to be the `b:bool = False` member, because removing it or changing its type removes the error.

**Comment by ailzhang** [comment] 2023-06-01 02:30
cc: @listerily , maybe this is related to the boolean type?

**Comment by listerily** [comment] 2023-06-01 04:04
> cc: @listerily , maybe this is related to the boolean type?

Seems yes. Maybe there is some special code generation rules related to `field`? I would look into it later.

**Comment by listerily** [comment] 2023-06-05 03:09
This issue is caused by `TaskCodeGenCUDA::create_intrinsic_load`. I'll keeping on working to solve that.

**Comment by listerily** [comment] 2023-06-05 08:02
Hi! Your issue has been solved and it has been merged into master. Additionally, default values are not supported in taichi dataclasses. Please remove default values in S like this:
```python
@ti.dataclass
class S:
    i: ti.i16
    b: bool
```

**Closed by listerily** 2023-06-05 08:02 UTC
