### ISSUE TITLE
[OS X Catalina] run fractal.py but report Segmentation fault: 11

### ISSUE THREAD

**Issue by bigrat911** [taichi-dev/taichi#343] opened 2020-01-06 13:15 UTC
**Describe the bug**
```
[Release mode]
[T 01/06/20 21:13:05.904] [logging.cpp:Logger@68] Taichi core started. Thread ID = 20802
[Taichi version 0.3.20, cpu only, commit 1c85d8e1]
[E 01/06/20 21:13:06.007] Received signal 11 (Segmentation fault: 11)

                            * Taichi Core - Stack Traceback *                             
==========================================================================================
|                       Module |  Offset | Function                                      |
|----------------------------------------------------------------------------------------|
*               taichi_core.so |     295 | taichi::signal_handler(int)                   |
*     libsystem_platform.dylib |      29 | (null)                                        |
*              libobjc.A.dylib | 194471675 | (null)                                      |
*                       AppKit |     139 | (null)                                        |
*                       AppKit |       0 | (null)                                        |
*                       AppKit |       0 | (null)                                        |
*                       AppKit |       0 | (null)                                        |
*                       AppKit |       0 | (null)                                        |
*                       AppKit |       0 | (null)                                        |
*                       AppKit |       0 | (null)                                        |
*                       AppKit |       0 | (null)                                        |
*                       AppKit |       0 | (null)                                        |
*                       AppKit |       0 | (null)                                        |
*                       AppKit |       0 | (null)                                        |
*                       AppKit |       0 | (null)                                        |
*               taichi_core.so |     746 | taichi::GUI::create_window()                  |
*               taichi_core.so |     296 | taichi::GUI::GUI(std::__1::basic_string<char, |
                                         |  std::__1::char_traits<char>, std::__1::alloc |
                                         | ator<char> > const&, int, int, bool)          |
*               taichi_core.so |      99 | pybind11::class_<taichi::GUI> pybind11::detai |
                                         | l::argument_loader<pybind11::detail::value_an |
                                         | d_holder&, std::__1::basic_string<char, std:: |
                                         | __1::char_traits<char>, std::__1::allocator<c |
                                         | har> >, taichi::VectorND<2, int, (taichi::Ins |
                                         | tSetExt)0> >::call_impl<void, void pybind11:: |
                                         | detail::initimpl::constructor<std::__1::basic |
                                         | _string<char, std::__1::char_traits<char>, st |
                                         | d::__1::allocator<char> >, taichi::VectorND<2 |
                                         | , int, (taichi::InstSetExt)0> >::execute<pybi |
                                         | nd11::class_<taichi::GUI>, 0>(pybind11::class |
                                         | _<taichi::GUI>&)::'lambda'(pybind11::detail:: |
                                         | value_and_holder&, std::__1::basic_string<cha |
                                         | r, std::__1::char_traits<char>, std::__1::all |
                                         | ocator<char> >, taichi::VectorND<2, int, (tai |
                                         | chi::InstSetExt)0>)&, 0ul, 1ul, 2ul, pybind11 |
                                         | ::detail::void_type>(void pybind11::detail::i |
                                         | nitimpl::constructor<std::__1::basic_string<c |
                                         | har, std::__1::char_traits<char>, std::__1::a |
                                         | llocator<char> >, taichi::VectorND<2, int, (t |
                                         | aichi::InstSetExt)0> >::execute<pybind11::cla |
                                         | ss_<taichi::GUI>, 0>(pybind11::class_<taichi: |
                                         | :GUI>&)::'lambda'(pybind11::detail::value_and |
                                         | _holder&, std::__1::basic_string<char, std::_ |
                                         | _1::char_traits<char>, std::__1::allocator<ch |
                                         | ar> >, taichi::VectorND<2, int, (taichi::Inst |
                                         | SetExt)0>)&, std::__1::integer_sequence<unsig |
                                         | ned long, 0ul, 1ul, 2ul>, pybind11::detail::v |
                                         | oid_type&&)                                   |
*               taichi_core.so |     153 | void pybind11::cpp_function::initialize<void  |
                                         | pybind11::detail::initimpl::constructor<std:: |
                                         | __1::basic_string<char, std::__1::char_traits |
                                         | <char>, std::__1::allocator<char> >, taichi:: |
                                         | VectorND<2, int, (taichi::InstSetExt)0> >::ex |
                                         | ecute<pybind11::class_<taichi::GUI>, 0>(pybin |
                                         | d11::class_<taichi::GUI>&)::'lambda'(pybind11 |
                                         | ::detail::value_and_holder&, std::__1::basic_ |
                                         | string<char, std::__1::char_traits<char>, std |
                                         | ::__1::allocator<char> >, taichi::VectorND<2, |
                                         |  int, (taichi::InstSetExt)0>), void, pybind11 |
                                         | ::detail::value_and_holder&, std::__1::basic_ |
                                         | string<char, std::__1::char_traits<char>, std |
                                         | ::__1::allocator<char> >, taichi::VectorND<2, |
                                         |  int, (taichi::InstSetExt)0>, pybind11::name, |
                                         |  pybind11::is_method, pybind11::sibling, pybi |
                                         | nd11::detail::is_new_style_constructor>(pybin |
                                         | d11::class_<taichi::GUI>&&, void (*)(pybind11 |
                                         | ::detail::value_and_holder&, std::__1::basic_ |
                                         | string<char, std::__1::char_traits<char>, std |
                                         | ::__1::allocator<char> >, taichi::VectorND<2, |
                                         |  int, (taichi::InstSetExt)0>), pybind11::name |
                                         |  const&, pybind11::is_method const&, pybind11 |
                                         | ::sibling const&, pybind11::detail::is_new_st |
                                         | yle_constructor const&)::'lambda'(pybind11::d |
                                         | etail::function_call&)::operator()(pybind11:: |
                                         | detail::function_call&) const                 |
*               taichi_core.so |    2874 | pybind11::cpp_function::dispatcher(_object*,  |
                                         | _object*, _object*)                           |
*                       python |     437 | (null)                                        |
*                       python |     111 | (null)                                        |
*                       python |     130 | (null)                                        |
*                       python |     130 | (null)                                        |
*                       python |     422 | (null)                                        |
*                       python |     241 | (null)                                        |
*                       python |     179 | (null)                                        |
*                       python |     453 | (null)                                        |
*                       python |   46092 | (null)                                        |
*                       python |     414 | (null)                                        |
*                       python |     231 | (null)                                        |
*                       python |     193 | (null)                                        |
*                       python |     241 | (null)                                        |
*                       python |     179 | (null)                                        |
*                       python |     453 | (null)                                        |
*                       python |   46336 | (null)                                        |
*                       python |     414 | (null)                                        |
*                       python |     256 | (null)                                        |
*                       python |     391 | (null)                                        |
*                       python |    9663 | (null)                                        |
*                       python |     125 | (null)                                        |
*                libdyld.dylib |       1 | (null)                                        |
*                          ??? |       2 | (null)                                        |
```
==========================================================================================

**To Reproduce**
python examples/fractal.py

**Comment by no-materials** [comment] 2020-01-06 17:37
Same issue on Mac OSX Catalina.

**Comment by yuanming-hu** [comment] 2020-01-06 17:41
Thanks for reporting. This is a known issue. More details: https://github.com/yuanming-hu/taichi/issues/313

**Comment by Icemap** [comment] 2020-01-08 01:27
Got same error in 10.14.
Follow your [taichi help document] (https://taichi.readthedocs.io/en/latest/hello.html).
Did I need install anything else?

**Comment by mfzMineGit** [comment] 2020-01-08 03:05
Got same error in [Linux release_server 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux]
Do I need to install anything else?

**Comment by oeway** [comment] 2020-01-09 11:20
Same here, although mine is macOS Mojave (version 10.14.5).

**Comment by Ljw127** [comment] 2020-01-10 05:12
In the same situation, my version is 10.14.6, isn't it working after 10.14?

**Comment by lisheng89** [comment] 2020-01-10 11:07
on OS X Catalina,  use apple default python3 install taichi, and run the code with `python3 xx.py` could solve it. 

python3 version
```
Python 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
````
mac os version
10.15.2

**Comment by yuanming-hu** [comment] 2020-01-11 05:28
@lisheng89 Could you confirm that `fractal.py` (which creates a GUI) works on your OS X Catalina 10.15.2? A lot of users reported that the GUI system does not work on Catalina.

**Comment by lisheng89** [comment] 2020-01-11 12:48
@yuanming-hu  `fractal.py` works well on my OS X Catalina 10.15.2

<img width="1502" alt="截屏2020-01-11下午8 46 42" src="https://user-images.githubusercontent.com/43165580/72204499-88f88480-34b3-11ea-9708-ca9359cc87c4.png">

**Comment by yuanming-hu** [comment] 2020-01-11 16:36
Hi guys, we have released v0.3.21 for OS X (thanks to @k-ye), which might have fixed this issue. However, we cannot test on every OS X version. Could you update and let us know if this issue is resolved?

**Comment by no-materials** [comment] 2020-01-12 11:23
I can confirm that the issue is resolved for OS X Catalina v10.15.1
<img width="792" alt="Screenshot 2020-01-12 at 1 21 12 PM" src="https://user-images.githubusercontent.com/16938952/72218014-a0c91a80-353e-11ea-9070-181a1ad53b97.png">

Thanks for the fix!

**Comment by oeway** [comment] 2020-01-12 11:28
hi @yuanming-hu Thanks for working on this, I can also confirm that this issue is resolved on macOS Mojave (10.14.5). The fractal example works now, cheers!

**Comment by yuanming-hu** [comment] 2020-01-12 16:06
Fantastic! I believe we can close this issue now. Credits go to @k-ye .

**Closed by yuanming-hu** 2020-01-12 16:06 UTC

**Comment by Ljw127** [comment] 2020-01-13 02:52
Thank you, using the new version of "taichi_nightly_0.3.21" effectively solved my problem! Sorry! I did n’t get an instant response on weekends. I saw your email at the company this morning! I tried to switch to "taichi_nightly_0.3.21", she can work on my mac ox Mojae 10.14.6 version, thank you again




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yuanming Hu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月11日(星期六) 中午1:28
收件人:&nbsp;"taichi-dev/taichi"<taichi@noreply.github.com&gt;;
抄送:&nbsp;"李金伟"<1311353736@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [taichi-dev/taichi] [OS X Catalina] run fractal.py but report Segmentation fault: 11 (#343)




@lisheng89 Could you confirm that fractal.py (which creates a GUI) works on your OS X Catalina 10.15.2? A lot of users reported that the GUI system does not work on Catalina.

**Comment by Ljw127** [comment] 2020-01-13 02:54
Thank you, using the new version of "taichi_nightly_0.3.21" effectively solved my problem! Sorry! I did n’t get an instant response on weekends. I saw your email at the company this morning! I tried to switch to "taichi_nightly_0.3.21", she can work on my mac ox Mojae 10.14.6 version, thank you again




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Wei Ouyang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月12日(星期天) 晚上7:28
收件人:&nbsp;"taichi-dev/taichi"<taichi@noreply.github.com&gt;;
抄送:&nbsp;"李金伟"<1311353736@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [taichi-dev/taichi] [OS X Catalina] run fractal.py but report Segmentation fault: 11 (#343)




hi @yuanming-hu Thanks for working on this, I can also confirm that this issue is resolved on macOS Mojave (10.14.5). The fractal example works now, cheers!

**Comment by Ljw127** [comment] 2020-01-13 02:59
Thank you, using the new version of "taichi_nightly_0.3.21" effectively solved my problem! Sorry! I did n’t get an instant response on weekends. I saw your email at the company this morning! I tried to switch to "taichi_nightly_0.3.21", she can work on my mac ox Mojae 10.14.6 version, thank you again




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Gerasimos Kougianos"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月12日(星期天) 晚上7:23
收件人:&nbsp;"taichi-dev/taichi"<taichi@noreply.github.com&gt;;
抄送:&nbsp;"李金伟"<1311353736@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [taichi-dev/taichi] [OS X Catalina] run fractal.py but report Segmentation fault: 11 (#343)




I can confirm that the issue is resolved for OS X Catalina v10.15.1
 
 
Thanks for the fix!

**Comment by bigrat911** [comment] 2020-01-14 02:56
> Hi guys, we have released v0.3.21 for OS X (thanks to @k-ye), which might have fixed this issue. However, we cannot test on every OS X version. Could you update and let us know if this issue is resolved?

Awesome! Thanks!

**Comment by simbaforrest** [comment] 2020-06-30 06:19
@yuanming-hu First thanks for the great work. 

Although this issue seems addressed in OS X, it still seems to persist for Ubuntu. Any suggestions on how to resolve the issue?

- I am using a remote workstation (Linux 5.0.0-31-generic #33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux). 

- I installed taichi by "python3 -m pip install taichi"

Following is the full console output.

~/code/taichi/examples$ python fractal.py
[Taichi] mode=release
[Taichi] version 0.6.14, llvm 10.0.0, commit c83a7e3d, python 3.7.6
MoTTY X11 proxy: Unsupported authorisation protocol
[Taichi] Starting on arch=cuda
MoTTY X11 proxy: Unsupported authorisation protocol
[E 06/30/20 02:10:18.331] Received signal 11 (Segmentation fault)


***********************************
* Taichi Compiler Stack Traceback *
***********************************
/home/ai4ce/.conda/envs/robvis/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
/home/ai4ce/.conda/envs/robvis/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so: taichi::signal_handler(int)
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fa467404f20]
/home/ai4ce/.conda/envs/robvis/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so: taichi::GUI::create_window()
/home/ai4ce/.conda/envs/robvis/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so: taichi::GUI::GUI(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, bool)
/home/ai4ce/.conda/envs/robvis/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so(+0x930a2c) [0x7fa4549b2a2c]
/home/ai4ce/.conda/envs/robvis/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so(+0x93091f) [0x7fa4549b291f]
/home/ai4ce/.conda/envs/robvis/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so(+0x7c85df) [0x7fa45484a5df]
python(_PyMethodDef_RawFastCallDict+0x265) [0x55d16f89da55]
python(_PyCFunction_FastCallDict+0x21) [0x55d16f89dbd1]
python(_PyObject_Call_Prepend+0x63) [0x55d16f89b943]
python(PyObject_Call+0x6e) [0x55d16f88eb9e]
python(+0xb6726) [0x55d16f81b726]
python(_PyObject_FastCallKeywords+0x128) [0x55d16f8dae28]
python(_PyEval_EvalFrameDefault+0x52cf) [0x55d16f92ae8f]
python(_PyEval_EvalCodeWithName+0x2f9) [0x55d16f87f6f9]
python(_PyFunction_FastCallDict+0x400) [0x55d16f880a30]
python(_PyObject_Call_Prepend+0x63) [0x55d16f89b943]
python(+0x17506a) [0x55d16f8da06a]
python(_PyObject_FastCallKeywords+0x128) [0x55d16f8dae28]
python(_PyEval_EvalFrameDefault+0x5817) [0x55d16f92b3d7]
python(_PyEval_EvalCodeWithName+0x2f9) [0x55d16f87f6f9]
python(PyEval_EvalCodeEx+0x44) [0x55d16f8805f4]
python(PyEval_EvalCode+0x1c) [0x55d16f88061c]
python(+0x21c974) [0x55d16f981974]
python(PyRun_FileExFlags+0xa1) [0x55d16f98bcf1]
python(PyRun_SimpleFileExFlags+0x1c3) [0x55d16f98bee3]
python(+0x227f95) [0x55d16f98cf95]
python(_Py_UnixMain+0x3c) [0x55d16f98d0bc]
/lib/x86_64-linux-gnu/libc.so.6: __libc_start_main
python(+0x1d0990) [0x55d16f935990]

Internal Error occurred, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting

**Comment by simbaforrest** [comment] 2020-06-30 06:52
Sorry I solved the above problem by adding the following. Apparently it was related to the OpenGL issue, even though the error message does not indicate that.

> export TI_ENABLE_OPENGL=0

> @yuanming-hu First thanks for the great work.
> 
> Although this issue seems addressed in OS X, it still seems to persist for Ubuntu. Any suggestions on how to resolve the issue?
> 
> * I am using a remote workstation (Linux 5.0.0-31-generic #33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux).
> * I installed taichi by "python3 -m pip install taichi"
> 
> Following is the full console output.
> 
> ~/code/taichi/examples$ python fractal.py
> [Taichi] mode=release
> [Taichi] version 0.6.14, llvm 10.0.0, commit [c83a7e3](https://github.com/taichi-dev/taichi/commit/c83a7e3df91019d035705ea1068a84f177e97a76), python 3.7.6
> MoTTY X11 proxy: Unsupported authorisation protocol
> [Taichi] Starting on arch=cuda
> MoTTY X11 proxy: Unsupported authorisation protocol
> [E 06/30/20 02:10:18.331] Received signal 11 (Segmentation fault)
> 
> * Taichi Compiler Stack Traceback *
> 
> /home/ai4ce/.conda/envs/robvis/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, bool)
> /home/ai4ce/.conda/envs/robvis/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so: taichi::signal_handler(int)
> /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fa467404f20]
> /home/ai4ce/.conda/envs/robvis/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so: taichi::GUI::create_window()
> /home/ai4ce/.conda/envs/robvis/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so: taichi::GUI::GUI(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, int, int, bool)
> /home/ai4ce/.conda/envs/robvis/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so(+0x930a2c) [0x7fa4549b2a2c]
> /home/ai4ce/.conda/envs/robvis/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so(+0x93091f) [0x7fa4549b291f]
> /home/ai4ce/.conda/envs/robvis/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so(+0x7c85df) [0x7fa45484a5df]
