### ISSUE TITLE
`ti.random(ti.i32)` always returns number of the same parity in the same thread

### ISSUE THREAD

**Issue by AmesingFlank** [taichi-dev/taichi#7182] opened 2023-01-16 21:49 UTC
Consider this program which generates 100 random ints and checks their parity (even or odd)
```py
import taichi as ti
x = [0,0]

for i in range(100):
    ti.init(ti.cuda, random_seed=i)

    @ti.kernel
    def k() -> int:
        return ti.random(ti.i32) % 2 
    p = k()
    x[p] += 1

print(x) 
```
This ends up printing 
```
[100, 0]
```

More generally, I noticed that, for a given thread, regardless of the random seed, the 1st random int it generates always has the same parity.

**Comment by lucifer1004** [comment] 2023-01-20 02:30
Ideas:

- Make a separate package and implement multiple RNGs with Taichi.

Resources:

- [RandomNumbers.jl](https://juliarandom.github.io/RandomNumbers.jl/stable/)
- [Mersenne Twister](http://www.math.sci.hiroshima-u.ac.jp/m-mat/MT/emt.html)
- [Generating multiple disjoint streams of pseudorandom number sequences](http://www.math.sci.hiroshima-u.ac.jp/m-mat/MT/JUMP/index.html)
- [TinyMT](http://www.math.sci.hiroshima-u.ac.jp/m-mat/MT/TINYMT/#:~:text=What%20is%20TinyMT,single%20precision%20floating%20point%20numbers.)

**Comment by lin-hitonami** [comment] 2023-01-20 03:22
@lucifer1004 Thanks! Would you like to contribute the RNGs to Taichi? Maybe we can let them be an official module (maybe `ti.math.random`?) in Taichi.

**Comment by lin-hitonami** [comment] 2023-01-20 03:32
We need to expose the random states of each thread to Python first if we want to implement RNGs outside the Taichi runtime.
https://github.com/taichi-dev/taichi/blob/800ff2b61c2403950da46d8d826b5022d85d2f84/taichi/runtime/llvm/runtime_module/runtime.cpp#L526-L532
https://github.com/taichi-dev/taichi/blob/800ff2b61c2403950da46d8d826b5022d85d2f84/taichi/runtime/llvm/runtime_module/runtime.cpp#L568

**Comment by lucifer1004** [comment] 2023-01-20 05:55
I would love to contribute, but I have higher priorities at the moment.

**Comment by lin-hitonami** [comment] 2023-01-20 06:18
@lucifer1004 Thank you very much! This is an old problem, and this doesn't need to be implemented very soon. Please contribute whenever is convenient to you!

**Comment by lucifer1004** [comment] 2023-01-22 15:35
As for this specific issue, the root cause is https://github.com/taichi-dev/taichi/blob/b48baebedf8726df8c898d2121b2f7c9538cc046/taichi/runtime/llvm/llvm_runtime_executor.cpp#L584

Then the `x` part of the initial random state is always an even number.

https://github.com/taichi-dev/taichi/blob/b48baebedf8726df8c898d2121b2f7c9538cc046/taichi/runtime/llvm/runtime_module/runtime.cpp#L534-L540

**Comment by bobcao3** [comment] 2023-01-26 07:57
We can move it to `1048391` which is a prime?

**Comment by lin-hitonami** [comment] 2023-01-28 03:55
@lucifer1004 @bobcao3 Thanks! Let me make a quick fix.

**Comment by lin-hitonami** [comment] 2023-01-28 05:20
BTW @bobcao3 it seems that the SPIRV-based backends don't use this random seed?

**Comment by bobcao3** [comment] 2023-01-28 06:07
> BTW @bobcao3 it seems that the SPIRV-based backends don't use this random seed?

They don't (and they uses a different algorithm), so this doesn't apply there.

**Comment by lucifer1004** [comment] 2023-01-31 01:27
Shall we close this issue and open a new one to track the RNG implementations? @lin-hitonami

**Comment by lin-hitonami** [comment] 2023-01-31 03:24
Good idea! Please open a new one!

**Closed by lin-hitonami** 2023-01-31 03:24 UTC
