### ISSUE TITLE
meet some problems of Voxel Challenge on taichi 1.0.1(Received signal 22)

### ISSUE THREAD

**Issue by LiujiaHuan** [taichi-dev/taichi#4900] opened 2022-05-01 05:21 UTC
**Describe the bug**
Running example1.py by using the pycharm with taichi 1.0.1,python 3.10.2,arch=cuda,windows and  got many errors .
(I have tried to switch python version,it still didn't work)
After I switch the taichi to <kbd>1.0.0</kbd> **it did't report errors and program runs correctly.**
So,what is going on here?
I have seen <a href = "https://docs.taichi-lang.org/lang/articles/install">https://docs.taichi-lang.org/lang/articles/install</a>
But it didn't mentioned  "Received signal 22 (SIGABRT)"

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
C:\Users\13956\Desktop\My_taichi-main\venv\Scripts\python.exe C:/Users/13956/Desktop/My_taichi-main/example6.py
[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, win, python 3.10.2
[Taichi] Starting on arch=cuda

====================================================
Camera:
* Drag with your left mouse button to rotate
* Press W/A/S/D/Q/E to move
====================================================

[I 05/01/22 13:01:55.935 2820] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device_creator.cpp:pick_physical_device@363] Found Vulkan Device 0 (NVIDIA GeForce RTX 3060 Laptop GPU)
[I 05/01/22 13:01:55.935 2820] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device_creator.cpp:pick_physical_device@363] Found Vulkan Device 1 (AMD Radeon(TM) Graphics)
[I 05/01/22 13:01:55.935 2820] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device_creator.cpp:create_logical_device@431] Vulkan Device "NVIDIA GeForce RTX 3060 Laptop GPU" supports Vulkan 0 version 1.3.194
[E 05/01/22 13:01:56.036 2820] Received signal 22 (SIGABRT)


***********************************
* Taichi Compiler Stack Traceback *
***********************************
A s s e r t i o n   f a i l e d :   m _ V u l k a n F u n c t i o n s . v k G e t D e v i c e B u f f e r M e m o r y R e q u i r e m e n t s   ! =   n u l l p t r ,   f i l e   D : / a / t a i c h i / t a i c h i / e x t e r n a l / V u l k a n M e m o r y A l l o c a t o r / i n c l u d e \ v k _ m e m _ a l l o c . h ,   l i n e   1 4 4 4 0 
 0x7fff9243447a: taichi::lang::Program::get_llvm_program_impl in taichi_core.pyd
0x7ff82c1e1881: raise in ucrtbase.dll
0x7ff82c1e2851: abort in ucrtbase.dll
0x7ff82c1e41b5: get_wpgmptr in ucrtbase.dll
0x7ff82c1e44f1: wassert in ucrtbase.dll
0x7fff926bb730: taichi::lang::vulkan::VulkanDeviceCreator::~VulkanDeviceCreator in taichi_core.pyd
0x7fff926bf415: taichi::lang::vulkan::VulkanDeviceCreator::~VulkanDeviceCreator in taichi_core.pyd
0x7fff92694e40: taichi::lang::vulkan::VkRuntime::get_root_buffer_size in taichi_core.pyd
0x7fff926a8bd7: taichi::lang::vulkan::VulkanDeviceCreator::VulkanDeviceCreator in taichi_core.pyd
0x7fff925a0eee: taichi::ui::vulkan::AppContext::init in taichi_core.pyd
0x7fff925ac6fd: taichi::ui::VboHelpers::size in taichi_core.pyd
0x7fff925ac388: taichi::ui::VboHelpers::size in taichi_core.pyd
0x7fff926f2327: PyInit_taichi_core in taichi_core.pyd
0x7fff926ce2dd: PyInit_taichi_core in taichi_core.pyd
0x7fffc0d9d8b6: PyObject_RichCompareBool in python310.dll
0x7fffc0de1f4f: PyObject_MakeTpCall in python310.dll
0x7fffc0f1cd11: Py_gitversion in python310.dll
0x7fffc0e58e80: PyVectorcall_Call in python310.dll
0x7fffc0e58c63: PyObject_Call in python310.dll
0x7fffc0ddc07d: PyType_GenericNew in python310.dll
0x7fffc0ddc780: PyType_GenericNew in python310.dll
0x7fff926c8724: PyInit_taichi_core in taichi_core.pyd
0x7fffc0dec2ba: PyEval_EvalFrameDefault in python310.dll
0x7fffc0de7227: PyFunction_Vectorcall in python310.dll
0x7fffc0ddc12e: PyType_GenericNew in python310.dll
0x7fffc0ddc780: PyType_GenericNew in python310.dll
0x7fffc0de1f4f: PyObject_MakeTpCall in python310.dll
0x7fffc0def0e5: PyEval_EvalFrameDefault in python310.dll
0x7fffc0de7227: PyFunction_Vectorcall in python310.dll
0x7fffc0ddc12e: PyType_GenericNew in python310.dll
0x7fffc0ddc780: PyType_GenericNew in python310.dll
0x7fffc0de1f4f: PyObject_MakeTpCall in python310.dll
0x7fffc0def0e5: PyEval_EvalFrameDefault in python310.dll
0x7fffc0dc617d: PyMapping_Check in python310.dll
0x7fffc0e0e05e: PyEval_EvalCode in python310.dll
0x7fffc0e0d1f2: Py_BuildValue in python310.dll
0x7fffc0e0d172: Py_BuildValue in python310.dll
0x7fffc0df8518: PyDict_DelItemString in python310.dll
0x7fffc0df8279: PyRun_SimpleFileObject in python310.dll
0x7fffc0df80bc: PyRun_AnyFileObject in python310.dll
0x7fffc0df8fdb: PyList_GetItem in python310.dll
0x7fffc0df8e97: PyList_GetItem in python310.dll
0x7fffc0df9e28: Py_RunMain in python310.dll
0x7fffc0df9cb9: Py_RunMain in python310.dll
0x7fffc0df96d1: Py_Main in python310.dll
0x7ff69ba01230: Unknown Function in python.exe
0x7ff82df47034: BaseThreadInitThunk in KERNEL32.DLL
0x7ff82e262651: RtlUserThreadStart in ntdll.dll

Internal error occurred. Check out this page for possible solutions:
https://docs.taichi-lang.org/lang/articles/install
...
```
btw,on my report log here is full of unreadable marks
<kbd>A s s e r t i o n   f a i l e d :   m _ V u l k a n F u n c t i o n s . v k G e t D e v i c e B u f f e r M e m o r y R e q u i r e m e n t s   ! =   n u l l p t r ,   f i l e   D : / a / t a i c h i / t a i c h i / e x t e r n a l / V u l k a n M e m o r y A l l o c a t o r / i n c l u d e \ v k _ m e m _ a l l o c . h ,   l i n e   1 4 4 4 0 </kbd>

**Comment by quadpixels** [comment] 2022-05-01 09:23
Same here, `Assertion failed: m_VulkanFunctions.vkGetDeviceBufferMemoryRequirements != nullptr, file C:\Users\nitroglycerine\taichi\external\VulkanMemoryAllocator\include\vk_mem_alloc.h, line 14440`

**Comment by birepeople** [comment] 2022-05-02 15:04
same here, and  I check and meets the same problem for cpu,vulkan,gpu arch.

**Comment by R366Y** [comment] 2022-05-02 18:03
I got this:

```
/home/r366y/PycharmProjects/testprj/venv/bin/python /home/r366y/PycharmProjects/testprj/fractal3d.py
[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, linux, python 3.10.4
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[Taichi] Starting on arch=vulkan
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

python: /home/dev/taichi/external/VulkanMemoryAllocator/include/vk_mem_alloc.h:14440: void VmaAllocator_T::ValidateVulkanFunctions(): Assertion `m_VulkanFunctions.vkGetDeviceBufferMemoryRequirements != nullptr' failed.
[I 05/02/22 19:59:50.596 21187] [vulkan_device_creator.cpp:pick_physical_device@363] Found Vulkan Device 0 (Intel(R) HD Graphics 620 (KBL GT2))
[I 05/02/22 19:59:50.596 21187] [vulkan_device_creator.cpp:pick_physical_device@363] Found Vulkan Device 1 (NVIDIA GeForce 940MX)
[I 05/02/22 19:59:50.596 21187] [vulkan_device_creator.cpp:pick_physical_device@363] Found Vulkan Device 2 (llvmpipe (LLVM 13.0.1, 256 bits))
[I 05/02/22 19:59:50.597 21187] [vulkan_device_creator.cpp:create_logical_device@431] Vulkan Device "NVIDIA GeForce 940MX" supports Vulkan 0 version 1.3.194

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by bobcao3** [comment] 2022-05-03 01:37
Duplicate of https://github.com/taichi-dev/taichi/issues/4891 , fixed in https://github.com/taichi-dev/taichi/pull/4893

**Closed by bobcao3** 2022-05-03 01:37 UTC
Labels: question

**Comment by Smethan** [comment] 2022-05-03 21:08
It looks like this wasn't actually fixed, I compiled the latest commit and still got the same error:
```
[Taichi] version 1.0.2, llvm 10.0.0, commit 77d5d3a3, win, python 3.10.2
[Taichi] Starting on arch=vulkan
[I 05/03/22 15:56:44.887 19916] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device_creator.cpp:pick_physical_device@364] Found Vulkan Device 0 (AMD Radeon RX 5600 XT)
[I 05/03/22 15:56:44.887 19916] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device_creator.cpp:find_queue_families@142] Async compute queue 1, graphics queue 0
[I 05/03/22 15:56:44.887 19916] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device_creator.cpp:find_queue_families@142] Async compute queue 1, graphics queue 0
[I 05/03/22 15:56:44.887 19916] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device_creator.cpp:create_logical_device@432] Vulkan Device "AMD Radeon RX 5600 XT" supports Vulkan 0 version 1.3.203
Assertion failed: m_VulkanFunctions.vkGetDeviceBufferMemoryRequirements != nullptr, file D:/a/taichi/taichi/external/VulkanMemoryAllocator/include\vk_mem_alloc.h, line 14440
```
Vulkan API: 1.3.203

It could possibly have something to do with me having an AMD GPU, but given that its the same error the folks above me got on NVIDIA GPUs I highly doubt it

**Comment by bobcao3** [comment] 2022-05-10 06:09
@Smethan  that is quite baffling... Can you try to add ```TI_WARN(“Vulkan funcptr {}”, (void*)table.vkGetDeviceBufferMemoryRequirements)``` of [taichi/backends/vulkan/vulkan_device.cpp](https://github.com/taichi-dev/taichi/pull/4893/files#diff-7dd0fe29e58de35b44f74155b97859fd20ca16ae5abfb3a39b750a1d66712af9) so that we can confirm which pointer we have acquired? Since the driver is reporting version 1.3, then these two function pointers must exist because they are in core.

**Comment by Smethan** [comment] 2022-05-10 19:54
I have no idea what I have done in the week since I posted that to anger my windows machine, but I cannot for the life of me get this to build, even just pulling from master wont compile, so I can't really test it at the moment. In the mean time, if you can compile it with that line in there and send it my way I'd be happy to run it.

**Comment by Smethan** [comment] 2022-05-10 22:19
Scratch that last comment, after a few hours of finagling I was able to get it to compile and this is the output I got:
```
[Taichi] version 1.0.2, llvm 10.0.0, commit e7d0b4f0, win, python 3.10.2
[Taichi] Starting on arch=vulkan
[I 05/10/22 17:11:56.438 3120] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device_creator.cpp:pick_physical_device@364] Found Vulkan Device 0 (AMD Radeon RX 5600 XT)
[I 05/10/22 17:11:56.438 3120] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device_creator.cpp:find_queue_families@142] Async compute queue 1, graphics queue 0
[I 05/10/22 17:11:56.438 3120] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device_creator.cpp:find_queue_families@142] Async compute queue 1, graphics queue 0
[I 05/10/22 17:11:56.439 3120] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device_creator.cpp:create_logical_device@432] Vulkan Device "AMD Radeon RX 5600 XT" supports Vulkan 0 version 1.3.203
[W 05/10/22 17:11:56.502 3120] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device.cpp:create_vma_allocator@2007] Vulkan funcptr 0x0
Assertion failed: m_VulkanFunctions.vkGetDeviceBufferMemoryRequirements != nullptr, file D:/a/taichi/taichi/external/VulkanMemoryAllocator/include\vk_mem_alloc.h, line 14440
```
with the only real different line there being 
```
[W 05/10/22 17:11:56.502 3120] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device.cpp:create_vma_allocator@2007] Vulkan funcptr 0x0
```
which doesn't really tell us much as far as I can tell. I'm personally a bit lost on what to do here, this low level stuff isn't exactly my area of expertise 😅

**Comment by bobcao3** [comment] 2022-05-11 02:13
This actually tells us quite a lot... Basically we can not acquire a function pointer that is supposed to be supported by Vulkan 1.3 Core, which means the driver isn't reporting its version capability correctly... 

Can you try to get a device profile using this tool here? https://vulkan.gpuinfo.org/download.php
If so that'd be great, thanks! @Smethan

**Comment by Smethan** [comment] 2022-05-11 02:20
Sure thing! Here you go:
[AMD Radeon RX 5600 XT.txt](https://github.com/taichi-dev/taichi/files/8666185/AMD.Radeon.RX.5600.XT.txt)
@bobcao3

**Comment by bobcao3** [comment] 2022-05-11 02:21
Also let's move this to #4951

**Comment by quadpixels** [comment] 2022-05-11 06:52
Interestingly I got the same error message `[W 05/10/22 23:48:56.686 10912] [vulkan_device.cpp:taichi::lang::vulkan::VulkanDevice::create_vma_allocator@2012] Vulkan funcptr 0x0`

GPU is Radeon RX 5500. 
[AMD Radeon RX 5500.json.txt](https://github.com/taichi-dev/taichi/files/8667416/AMD.Radeon.RX.5500.json.txt)
