### ISSUE TITLE
Use `const Type *`  instead of `Type *` when referencing a type

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#6930] opened 2022-12-20 07:31 UTC
**Concisely describe the proposed feature**
We should use `const Type *` instead of `Type *` when referencing a type because a `Type` should not be altered after being created in the `TypeFactory`.

**Comment by strongoier** [comment] 2022-12-20 07:36
Duplicate of #5167?

**Closed** 2022-12-20 07:37 UTC
Labels: feature request
