### ISSUE TITLE
taichi failed to build on Windows with MSVC on latest version 5953e03

### ISSUE THREAD

**Issue by YangYang129** [taichi-dev/taichi#3743] opened 2021-12-08 06:19 UTC
taichi failed to build on Windows with MSVC on latest version 5953e03, dependence [**taichi-llvm-10.0.0-msvc2019** ](https://github.com/taichi-dev/taichi_assets/releases/download/llvm10/taichi-llvm-10.0.0-msvc2019.zip) and [**clang-10.0.0-win** ](https://github.com/taichi-dev/taichi_assets/releases/download/llvm10/clang-10.0.0-win.zip), "error STL1000: Unexpected compiler version, expected Clang 11.0.0 or newer.". But install LLVM-11.0.0-win64 and build still failed "error: [Errno 2] No such file or directory: 'runtimes/Release/taichi_core.dll"
taichi successfully build on Windows with MSVC on version 4590adc when dependence taichi-llvm-10.0.0-msvc2019 and clang-10.0.0-win. Could you please help look at this issue? Thank you very much.

Environment:
Compiler version: VS2019 (16.11.5)
Operating system: Windows server 2019

**Reproduce steps:**
1. git clone https://github.com/taichi-dev/taichi F:\gitP\taichi-dev\taichi
2. cd F:\gitP\taichi-dev\taichi
3. git submodule update --init --recursive
4. pip3 install --user gitpython
5. pip3 install --user pybind11
6. set PATH=F:\gitP\taichi-dev\tools\taichi-llvm-10.0.0-msvc2019\bin;%PATH%
7. set PATH=F:\gitP\taichi-dev\tools\clang-10.0.0-win\bin;%PATH%
8. python -m pip install -r requirements_dev.txt
9. python -m pip install -r requirements_test.txt
10. python -c "import taichi"
11. python -m pip install -v .
**Error log:**
Error "error STL1000: Unexpected compiler version, expected Clang 11.0.0 or newer." [log.log](https://github.com/taichi-dev/taichi/files/7673285/log.log)

I install [LLVM-11.0.0-win64](https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/LLVM-11.0.0-win64.exe), set environment variable and build
**6. set PATH=F:\gitP\taichi-dev\tools\taichi-llvm-10.0.0-msvc2019\bin;%PATH%
7. set PATH=F:\LLVM-11.0.0-win64\bin;%PATH%**
8. python -c "import taichi"
9. python -m pip install -v .

**Error log:**
Error "error: [Errno 2] No such file or directory: 'runtimes/Release/taichi_core.dll'" [log2.log](https://github.com/taichi-dev/taichi/files/7673727/log2.log)

Is this error due to inconsistent versions of the clang11.0.0 and taichi-llvm-10.0.0-msvc2019? I did not find the installation package of taichi-llvm-11.0.0-msvc2019. Could you please help look at this issue? Thank you very much

**Comment by qiao-bo** [comment] 2021-12-08 06:41
Hi, thanks for reporting, we will have a look at this. If i understood correctly, version at `590adc` worked for you?

**Comment by YangYang129** [comment] 2021-12-08 07:02
@qiao-bo Thanks for your reply. When using same build steps, I can build successfully on version 4590adc, but build failed on latest version 5953e03. I need to use latest version to running build and test.

**Comment by qiao-bo** [comment] 2021-12-08 07:24
@YangYang129, [recently](https://github.com/taichi-dev/taichi/pull/3712/files) we changed Ninja as the cmake generator to speedup incremental build. The error is from Ninja picking up Clang-10 in your path. Could you fix this by using Clang>=11 (sorry. currently we don't have a prebuilt pacakge)? or try to run the build inside visual studio environment?

**Comment by bobcao3** [comment] 2021-12-13 05:29
This is also a bug in our setup.py, should be fixed when https://github.com/taichi-dev/taichi/pull/3735 is merged. We also need to update the installation docs

**Comment by qiao-bo** [comment] 2021-12-20 10:25
Hi, FYI, our windows installation [doc](https://docs.taichi.graphics/lang/articles/contribution/dev_install#build-taichi-from-source) has been updated.

**Comment by gaoxinge** [comment] 2021-12-20 15:55
@qiao-bo @bobcao3 I doubt that the problem is caused by the dismatch of clang version and stl version, not by the installation script or `setup.py`. 

## reproduce and error

My environment is 

- VS2019
- [clang 10.0.0](https://github.com/taichi-dev/taichi_assets/releases/download/llvm10/clang-10.0.0-win.zip)

and the smallest piece of code to reproduce the problem is below:

```cpp
// main.cpp
#include <string>
#include <iostream>

int main() {
    std::string s = "abc";
    std::cout << s << std::endl;
    return 0;
}
```

```
$ clang --version
clang version 10.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\gaoxinge\clang-10.0.0-win\bin
$ clang main.cpp -o main
In file included from main.cpp:1:
In file included from C:\gaoxinge\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\string:9:
C:\gaoxinge\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h:551:2: error: STL1000: Unexpected compiler version, expected Clang 11.0.0 or newer.
#error STL1000: Unexpected compiler version, expected Clang 11.0.0 or newer.
 ^
1 error generated.
```

## my solution

So I update the clang from 10.0.0 to 11.0.0 by download, install the [Windows (64-bit) Pre-Built Binaries](https://releases.llvm.org/download.html#11.0.0) and add the bin directory to `$PATH`. This can make the `python setup.py develop` work around, but with many compilation warnings.

**Comment by bobcao3** [comment] 2021-12-21 02:38
> 

Please refer to the latest installation guide. On windows you need to use the visual studio env to build on windows. Clang 10/11 is required, but it is not used for building the C++ source code.

**Comment by bobcao3** [comment] 2021-12-21 02:39
@gaoxinge Also if you have already added clang or similar to PATH, please remove them

**Comment by gaoxinge** [comment] 2021-12-21 13:22
@bobcao3 Thanks for your advice. I have already successfully compiled source codes  by following the [doc](https://github.com/taichi-dev/taichi/blob/f403b25161446409daa9708d8cbe8869a39efb4f/docs/lang/articles/contribution/dev_install.md).

There are some improvements for the doc:

1. Change `<Path to the extrated LLVM binary>` to `<Path to LLVM 10>` in sentence below which may be more accurate, because we need export llvm directory, not only llvm bin. 

```
Add an environment variable `LLVM_DIR` with value `<Path to the extrated LLVM binary>`
```

2. There is a redundant `;` in `-DCLANG_EXECUTABLE=<Path to Clang 10>;/bin/clang.exe`.

```
1. Set-up the environment variable `TAICHI_CMAKE_ARGS` with value `-DCLANG_EXECUTABLE=<Path to Clang 10>;/bin/clang.exe -DLLVM_AS_EXECUTABLE=<Path to LLVM 10>/bin/llvm-as.exe`
```

Finally,  I am stuck at compile for some time, because there is a compiler warning treated as error by cl:

```
$ python setup.py develop
...
---------- Building extensions ----------------------------------------
[13/230] Building CXX object external\SPIRV-Tools\source\CMakeFiles\SPIRV-Tools-shared.dir\val\validate_image.cpp.obj
FAILED: external/SPIRV-Tools/source/CMakeFiles/SPIRV-Tools-shared.dir/val/validate_image.cpp.obj
...
C:\gaoxinge\github\taichi\external\SPIRV-Tools\source\val\validate_image.cpp(1563): error C2220: 以下警告被视为错误
C:\gaoxinge\github\taichi\external\SPIRV-Tools\source\val\validate_image.cpp(1563): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
...
```

So I add [/w](https://docs.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=msvc-170#remarks) in [TaichiCXXFlags.cmake](https://github.com/taichi-dev/taichi/blob/f403b25161446409daa9708d8cbe8869a39efb4f/cmake/TaichiCXXFlags.cmake) to suppress all compiler warnings like

```cmake
    if (MSVC)
        set(CMAKE_CXX_FLAGS
            "${CMAKE_CXX_FLAGS} /w /Zc:__cplusplus /std:c++17 /bigobj /wd4244 /wd4267 /nologo /Zi /D \"_CRT_SECURE_NO_WARNINGS\" /D \"_ENABLE_EXTENDED_ALIGNED_STORAGE\"")
    else()
```

**Comment by gaoxinge** [comment] 2022-04-15 17:37
@qiao-bo I have checked windows build by following [dev install doc](https://docs.taichi.graphics/lang/articles/dev_install), and it still works stably.

**Closed** 2022-04-16 03:27 UTC
Labels: potential bug
