### ISSUE TITLE
Assertion failed when exporting aot module after call Taichi function with Vulkan backend

### ISSUE THREAD

**Issue by zh0ngtian** [taichi-dev/taichi#5791] opened 2022-08-16 07:24 UTC
**Describe the bug**
There is assertion failure when exporting aot module after call Taichi function with Vulkan backend.

**To Reproduce**
```py
import taichi as ti

@ti.kernel
def taichi_norm(in_ten: ti.types.ndarray(), out_ten: ti.types.ndarray(), alpha: float, beta: float):
    for i, j, k in in_ten:
        out_ten[i, j, k] = in_ten[i, j, k] * alpha + beta

arch = ti.vulkan
ti.init(arch=arch)

in_ten = ti.ndarray(dtype=ti.f32, shape=(320, 320, 3))
out_ten = ti.ndarray(dtype=ti.f32, shape=(320, 320, 3))
alpha = 1.0 / 255
beta = 1.0

taichi_norm(in_ten, out_ten, alpha, beta)

m = ti.aot.Module(arch)
m.add_kernel(taichi_norm, template_args={
                    "in_ten": in_ten,
                    "out_ten": out_ten
                })
m.save("../models/taichi_aot", "")
```

**Log/Screenshots**
```
[Taichi] version 1.1.1, llvm 10.0.0, commit 5d91e969, osx, python 3.7.13
[Taichi] Starting on arch=vulkan
[I 08/16/22 15:24:22.990 8645743] [vulkan_device_creator.cpp:pick_physical_device@372] Found Vulkan Device 0 (Apple M1 Pro)
[I 08/16/22 15:24:22.990 8645743] [vulkan_device_creator.cpp:create_logical_device@440] Vulkan Device "Apple M1 Pro" supports Vulkan 0 version 1.1.216
[W 08/16/22 15:24:22.990 8645743] [vulkan_device_creator.cpp:create_logical_device@488] Potential non-conformant Vulkan implementation, enabling VK_KHR_portability_subset
[W 08/16/22 15:24:22.990 8645743] [vulkan_device_creator.cpp:create_logical_device@556] Taichi GPU GUI requires wide lines support
[E 08/16/22 15:24:23.010 8645743] [offload.cpp:visit@732] Assertion failure: cur_offloaded_stmt_ == nullptr


Traceback (most recent call last):
  File "test_taichi.py", line 54, in <module>
    test_norm(ti.vulkan)
  File "test_taichi.py", line 31, in test_norm
    "out_ten": out_ten
  File "/Users/zhongtian/.pyenv/versions/3.7.13/lib/python3.7/site-packages/taichi-1.1.1-py3.7-macosx-12.0-arm64.egg/taichi/aot/module.py", line 152, in add_kernel
    self._aot_builder.add(kernel_name, kernel.kernel_cpp)
RuntimeError: [offload.cpp:visit@732] Assertion failure: cur_offloaded_stmt_ == nullptr
```

**Additional comments**
There is no assertion failure if `taichi_norm(in_ten, out_ten, alpha, beta)` is commented.

There is no assertion failure if `arch = ti.cpu`.

**Comment by ailzhang** [comment] 2022-08-17 03:11
@zh0ngtian If you comment out `taichi_norm(in_ten, out_ten, alpha, beta)` line this should work. 

There's currently a bug in vulkan aot that JIT compilation and aot add_kernel doesn't work well together so maybe temporarily run them separately for now. We'll get that fixed in the next release. https://github.com/taichi-dev/taichi/issues/5699

**Comment by ailzhang** [comment] 2022-08-26 04:19
Closing this as a duplicate of #5699, @PGZXB is working on a fix for this issue. (Thanks!

**Closed by ailzhang** 2022-08-26 04:19 UTC
Labels: potential bug
