### ISSUE TITLE
Fail to setup dev env under Apple M1

### ISSUE THREAD

**Issue by WenheLI** [taichi-dev/taichi#3346] opened 2021-11-01 14:02 UTC
**Describe the bug**
I was trying to set up the dev env for my M1 Mac. However, I encountered the following error while running `python setup.py develop --user`

```bash
Building commit 470e47dcc8199d9bc14a6233a946093000260319
[  0%] Built target generate_commit_hash
/usr/local/bin/llvm-as: runtime_arm64.ll:2540:74: error: expected ')' at end of argument list
define void @Element_get_pcoord(%struct.PhysicalCoordinates* noalias sret(%struct.PhysicalCoordinates) align 4 %0, %struct.Element* %1) #0 {
```
My llvm is 10.0.0
And both C compiler and C++ compiler are 11.1.0
And the python version is 3.9.7.
Any one know how to fix it?

**Comment by k-ye** [comment] 2021-11-01 14:29
Hmm, what's your `/usr/local/bin/llvm-as --version`? Note that it might not pick up the correct binary.

Relevant issues:

* https://github.com/taichi-dev/taichi/issues/3320
* https://github.com/taichi-dev/taichi/issues/3183

**Comment by WenheLI** [comment] 2021-11-01 14:34
@k-ye - llvm-as aligns with llvm and both of them are 10.0.0. 
```bash
/usr/local/bin/llvm-as --version
LLVM (http://llvm.org/):
  LLVM version 10.0.0
  Optimized build with assertions.
  Default target: arm-apple-darwin21.1.0
  Host CPU: cyclone
```
Also the cmake prepare shows I am using the correct binaries:
```
---------- Running CMake prepare ----------------------------------------
-- The C compiler identification is Clang 11.1.0
-- The CXX compiler identification is Clang 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/homebrew/opt/llvm@11/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/homebrew/opt/llvm@11/bin/clang++ - skipped
```

Quite unsure where the problem is.

**Comment by k-ye** [comment] 2021-11-01 14:55
Huh, could you replace these with the actual command?

https://github.com/taichi-dev/taichi/blob/dfd1e4cb131be2380bd9f8df49b661bdc6dfc490/CMakeLists.txt#L99-L100

BTW, I don't think any of you has run into problems w/ clang-11 on M1? @sjwsl @ailzhang @Leonz5288  ?

**Comment by WenheLI** [comment] 2021-11-01 15:11
> Huh, could you replace these with the actual command?
> 
> https://github.com/taichi-dev/taichi/blob/dfd1e4cb131be2380bd9f8df49b661bdc6dfc490/CMakeLists.txt#L99-L100
> 
> BTW, I don't think any of you has run into problems w/ clang-11 on M1? @sjwsl @ailzhang @Leonz5288 ?

After explicitly replacing the clang-11, everything works. It seems like the CMake file does find the correct clang binary for compiling. Would also look into that if I got some time.

**Comment by sjwsl** [comment] 2021-11-01 15:24
> > Huh, could you replace these with the actual command?
> > https://github.com/taichi-dev/taichi/blob/dfd1e4cb131be2380bd9f8df49b661bdc6dfc490/CMakeLists.txt#L99-L100
> > 
> > BTW, I don't think any of you has run into problems w/ clang-11 on M1? @sjwsl @ailzhang @Leonz5288 ?
> 
> After explicitly replacing the clang-11, everything works. It seems like the CMake file does find the correct clang binary for compiling. Would also look into that if I got some time.

Cool! BTW, you can search for `llvm-as` and `clang` in `taichi/build/CMakeFiles/generate_llvm_runtime_x64.dir/build.make` after building with the original `CMakeLists.txt` to see which binaries are found, which may help you debug this issue.

**Comment by ifteene** [comment] 2021-11-02 12:11
Bio

**Comment by ailzhang** [comment] 2021-11-02 13:43
Now that I remember when we tried this on @rexwangcc 's laptop we also had to manually set to clang++11. Maybe a reordering (or better mechanism to find clang) is indeed needed. @sjwsl would you mind if I assign this to you and followup on this? Thanks a lot!

**Comment by sjwsl** [comment] 2021-11-02 14:00
> Now that I remember when we tried this on @rexwangcc 's laptop we also had to manually set to clang++11. Maybe a reordering (or better mechanism to find clang) is indeed needed. @sjwsl would you mind if I assign this to you and followup on this? Thanks a lot!

No problem. I thought about this issue but didn't have time to dive into it. Seems now it brings troubles to quite a few developers. Probably a version check is also useful, at least for users to better know what the problem is. Will deal with it soon.

**Closed** 2021-11-12 01:56 UTC
Labels: mac, potential bug, build

**Comment by izackwu** [comment] 2021-12-03 15:37
@frostming This solution works perfectly for me (on MacBook with M1X chips). Thank you!
