### ISSUE TITLE
Compiled kernel doesn't handle signess right.

### ISSUE THREAD

**Issue by feisuzhu** [taichi-dev/taichi#4986] opened 2022-05-16 10:40 UTC
**Describe the bug**
Subtracting an unsigned number behaves like subtracting signed number.

**To Reproduce**
Please post a **minimal sample code** to reproduce the bug.
The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the sample code **short** and **representative**.

```py
import taichi as ti
ti.init(arch=ti.cpu)

A = ti.field(ti.uint8, shape=())
B = ti.field(ti.uint16, shape=())

def step_raw():
    v: ti.uint16 = 1000
    v -= A[None]
    B[None] = v

step = ti.kernel(step_raw)


def main():
    A[None] = 255
    step()
    print(A[None], B[None])
    step_raw()
    print(A[None], B[None])

if __name__ == "__main__":
    main()
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

PyPI:
```
☁  taichi  python3 r2.py
[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, linux, python 3.8.10
[Taichi] Starting on arch=x64
255 1001
255 745
```
nightly:
```
☁  taichi  python3 r2.py
[Taichi] version 1.0.2, llvm 10.0.0, commit 22d18951, linux, python 3.8.10
[Taichi] Starting on arch=x64
255 1001
255 745
```

**Additional comments**
If possible, please also consider attaching the output of command `ti diagnose`. This produces the detailed environment information and hopefully helps us diagnose faster.

```
☁  taichi  ti diagnose
[Taichi] version 1.0.2, llvm 10.0.0, commit 22d18951, linux, python 3.8.10

*******************************************
**      Taichi Programming Language      **
*******************************************

Docs:   https://docs.taichi-lang.org/
GitHub: https://github.com/taichi-dev/taichi/
Forum:  https://forum.taichi.graphics/

Taichi system diagnose:

python: 3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0]
system: linux
executable: /usr/bin/python3
platform: Linux-5.4.0-110-generic-x86_64-with-glibc2.29
architecture: 64bit ELF
uname: uname_result(system='Linux', node='Proton', release='5.4.0-110-generic', version='#124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022', machine='x86_64', processor='x86_64')
locale: zh_CN.UTF-8
PATH: /home/proton/.cargo/bin:/home/proton/hammers/bin-vfio:/home/proton/hammers/bin-tun2socks:/home/proton/hammers/bin-texlive:/home/proton/hammers/bin-node:/home/proton/hammers/bin-local-python:/home/proton/hammers/bin-local-bin:/home/proton/hammers/bin-k8s:/home/proton/hammers/bin-go:/home/proton/hammers/bin:/home/proton/bin:/home/proton/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/proton/.fzf/bin
PYTHONPATH: ['/home/proton/.local/bin', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/proton/.local/lib/python3.8/site-packages', '/home/proton/source/tv', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal



import: <module 'taichi' from '/home/proton/.local/lib/python3.8/site-packages/taichi/__init__.py'>

cc: False
cpu: True
metal: False
opengl: True
cuda: True
vulkan: True

`glewinfo` not available: [Errno 2] No such file or directory: 'glewinfo'

Mon May 16 18:38:49 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P600         Off  | 00000000:0B:00.0  On |                  N/A |
| 37%   51C    P0    N/A /  N/A |    662MiB /  1997MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      4318      G   /usr/lib/xorg/Xorg                109MiB |
|    0   N/A  N/A      6259      G   /usr/lib/xorg/Xorg                463MiB |
|    0   N/A  N/A     12044      G   /usr/lib/firefox/firefox           34MiB |
|    0   N/A  N/A    149399      G   x-terminal-emulator                10MiB |
|    0   N/A  N/A   4178024      G   x-terminal-emulator                13MiB |
|    0   N/A  N/A   4182246      G   x-terminal-emulator                20MiB |
+-----------------------------------------------------------------------------+

[Taichi] version 1.0.2, llvm 10.0.0, commit 22d18951, linux, python 3.8.10

[Taichi] version 1.0.2, llvm 10.0.0, commit 22d18951, linux, python 3.8.10
[Taichi] Starting on arch=x64

[Taichi] version 1.0.2, llvm 10.0.0, commit 22d18951, linux, python 3.8.10
[Taichi] Starting on arch=opengl

[Taichi] version 1.0.2, llvm 10.0.0, commit 22d18951, linux, python 3.8.10
[Taichi] Starting on arch=cuda

[Taichi] version 1.0.2, llvm 10.0.0, commit 22d18951, linux, python 3.8.10

*******************************************
**      Taichi Programming Language      **
*******************************************

Docs:   https://docs.taichi-lang.org/
GitHub: https://github.com/taichi-dev/taichi/
Forum:  https://forum.taichi.graphics/

Running example minimal ...
[Taichi] Starting on arch=x64
42.0
>>> Running time: 0.25s
42

Consider attaching this log when maintainers ask about system information.
>>> Running time: 9.09s
```

If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.

**Comment by feisuzhu** [comment] 2022-05-16 10:48
BTW, the common issues link in bug report template is dead.

**Comment by feisuzhu** [comment] 2022-05-17 08:09
A simpler reproducing snippet:

```python
@ti.kernel
def test() -> ti.uint16:
    x: ti.uint16 = 1000
    y: ti.uint8 = 255
    ti.atomic_sub(x, y)
    return x
```

In current implementation the subtrahend `y` is first negated and then `atomic_add`ed to `x`, and `y` can overflow when negated.

**Comment by jim19930609** [comment] 2022-05-18 13:23
Hi feishuzhu, 
Thanks for reporting this issue. It's a fairly interesting problem and `y`'s overflow doesn't seem to be the only reason. If you try out `x: ti.uint16 = 1000` and `y : ti.uint8 = 1`, it yields 1255 instead of 999. 

The problem is that we're trying to cast the `1's complement` into an unsigned integer, which breaks the interpretation: 

<img width="347" alt="image" src="https://user-images.githubusercontent.com/22334008/169048132-fb432174-3f0b-4101-b50a-92db0b1c9b88.png">

The solution is to perform the type promotion (which inserts the "cast") for `y` before negating its value. Let me make a quick fix for this.

**Comment by ailzhang** [comment] 2022-05-20 06:11
Closing via #5011

**Closed by ailzhang** 2022-05-20 06:11 UTC
Labels: potential bug
