### ISSUE TITLE
Performance issue: Weird performance change with type casting

### ISSUE THREAD

**Issue by ifsheldon** [taichi-dev/taichi#2375] opened 2021-05-28 22:39 UTC
**Performance Issue**
Type casting sometimes seems to take a lot of overhead but sometimes it is not.

**Additional Context**
When I was doing some interpolations on "textures", I need to use a lot type casting between `float` and `int`, then I found some "interesting" performance changes after some changes to my code that is about type casting.

**To Reproduce**
My code is a bit long(100+ lines), so I pick up the changes I've made to my code and explain a bit my findings.
Originally, my code is the below. `sample_volume_trilinear` just samples a 3D scalar `ti.field` tri-linearly, and it takes float arguments.
```python
delta=0.001
@ti.func
def get_normal(x: int, y: int, z: float):
    x = float(x)  # 1
    y = float(y)  # 1
    dx = sample_volume_trilinear(x + delta, y, z) - sample_volume_trilinear(x - delta, y, z)  # 2
    dy = sample_volume_trilinear(x, y + delta, z) - sample_volume_trilinear(x, y - delta, z)  # 2
    dz = sample_volume_trilinear(x, y, z + delta) - sample_volume_trilinear(x, y, z - delta)  # 2
    n = ti.Vector([dx, dy, dz])
    return n / n.norm()
```
With that function, I got some runtime warnings, which basically state that on lines makred `1`, I tried to store float numbers in int variables, and on lines marked `2` I tried to convert implicitly convert ints to floats. But, that was not my intention. I, in a Pythonic lazy way, intended to make `x` and `y` hold float values. 

Then, I thought, okay fine, this function must be converted to C-like code so I cannot do such lazy conversions, so I change the code to be like this.
```python
delta = 0.001
@ti.func
def get_normal(x: int, y: int, z: float):
    xf = float(x) 
    yf = float(y)
    dx = sample_volume_trilinear(xf + delta, yf, z) - sample_volume_trilinear(xf - delta, y, z)
    dy = sample_volume_trilinear(xf, yf + delta, z) - sample_volume_trilinear(xf, yf - delta, z)
    dz = sample_volume_trilinear(xf, yf, z + delta) - sample_volume_trilinear(xf, yf, z - delta)
    n = ti.Vector([dx, dy, dz])
    return n / n.norm()
```
Now, I got rid of all runtime warnings, but I got ~40% fps decrease from ~58fps to ~36fps, which is weird for me, because in the original function, the number of casting operations should be at least the same as the number of the second version, but the first one runs much faster.

For the full code, please see my simplest trial on implementing Direct Volume Rendering with Taichi [here](https://github.com/ifsheldon/Differender/blob/DVR/src/hello.py) and checkout the differences between two commits(`9ffc3945` and `9aa7b64c`)

**Additional comments**
I know that I should not have used so many casting operations because I can optimize it by prestore cast float values, so I did it in my commits to my repo and my final version is the below. 
But, I think such performance changes are weird and you should look into it.
```python
@ti.func
def get_normal(x: float, y: float, z: float): # this runs at least as fast as the original one
    dx = sample_volume_trilinear(x + delta, y, z) - sample_volume_trilinear(x - delta, y, z)
    dy = sample_volume_trilinear(x, y + delta, z) - sample_volume_trilinear(x, y - delta, z)
    dz = sample_volume_trilinear(x, y, z + delta) - sample_volume_trilinear(x, y, z - delta)
    n = ti.Vector([dx, dy, dz])
    return n / n.norm()
```

**Comment by k-ye** [comment] 2021-05-29 13:20
Could you try `ti.init(print_ir=True, ...)` and see if the later case generates a lot more casts?

**Comment by ifsheldon** [comment] 2021-05-29 14:11
OK, I tried to print out the ir and here are the results.
The first version generates 22k lines of output totally while the second version gets 26k, but the first version's output has 108 `kernel` while the second one has 70 `kernel`. And I wasn't expecting so many differences.
[first.txt](https://github.com/taichi-dev/taichi/files/6564790/first.txt)
[second.txt](https://github.com/taichi-dev/taichi/files/6564792/second.txt)
You can also tried out my commit `9ffc3945`, but I think the results will be similar

**Comment by k-ye** [comment] 2021-05-29 14:19
Could you create a simple kernel that only uses `get_normal()` and then print the IR? It would be a lot easier to spot the difference this way.

**Comment by ifsheldon** [comment] 2021-05-29 16:20
With the simplest render kernel like below
```python
@ti.kernel
def simple_DVR():
    for x, y in pixels:
        idx_x = x // scaling
        idx_y = y // scaling
        max_marching_steps = int(slice_num / step_size)
        position = tl.vec3(idx_x, idx_y, 0.0)
        for step in range(max_marching_steps):
            normal = get_normal(idx_x, idx_y, position.z)
```
I got these two ir logs, but they both have 10k lines, and I don't see frame rate differences because both give 60fps.

[first.txt](https://github.com/taichi-dev/taichi/files/6564965/first.txt)
[second.txt](https://github.com/taichi-dev/taichi/files/6564966/second.txt)

**Comment by k-ye** [comment] 2021-05-31 00:46
Thanks! If you search for your kernel name `simple_DVR`, you would be able to see a series of transformed IR after each pass. E.g.

```
[I 05/29/21 19:17:55.684] [compile_to_offloads.cpp:operator()@22] [simple_DVR_c32_0] Bit struct stores optimized:
kernel {
  $0 = offloaded range_for(0, 1048576) grid_dim=2624 block_dim=128
  body {
    <i32> $1 = const [602]
    <i32> $2 = const [0]
    <i32> $3 = loop $0 index 0
    <i32> $4 = const [10]
    <i32> $5 = bit_sar $3 $4
    <i32> $6 = const [1023]
    <i32> $7 = bit_and $5 $6
    <i32> $8 = bit_and $3 $6
    <i32> $9 = const [920]
    <i32> $10 = cmp_lt $7 $9
    <i32> $11 = const [850]
    <i32> $12 = cmp_lt $8 $11
    <i32> $13 = bit_and $10 $12
    $14 : if $13 {
      $15 : for in range($2, $1) (vectorize 1) (bit_vectorize -1) block_dim=adaptive {
      }
    }
  }
}
```

The interesting bit is that `normal` wasn't get used anywhere, so Taichi aggressively optimized this kernel to a point where all the computations are eliminated. You can try writing `normal` back to some field. Basically we're trying to confirm if the slowness was indeed caused by the excessive casts.

**Comment by xumingkuan** [comment] 2021-05-31 07:47
I just took a brief look at here:

> OK, I tried to print out the ir and here are the results.
> The first version generates 22k lines of output totally while the second version gets 26k, but the first version's output has 108 `kernel` while the second one has 70 `kernel`. And I wasn't expecting so many differences.
> [first.txt](https://github.com/taichi-dev/taichi/files/6564790/first.txt)
> [second.txt](https://github.com/taichi-dev/taichi/files/6564792/second.txt)
> You can also tried out my commit `9ffc3945` of my repo, but I think the results will be similar

In the initial IR of `simple_DVR`, the first difference between them is
```
      @tmp114 = (cast_value<f32> @tmp114)
      @tmp115 = (cast_value<f32> @tmp115)
```
vs.
```
      @tmp117 = (cast_value<f32> @tmp114)
      $178 = alloca @tmp118
      @tmp118 = (cast_value<f32> @tmp115)
```
($178 is never used). After lower_ast (`Lowered`), these become
```
      $368 = local load [ [$359[0]]]
      $369 = cast_value<f32> $368
      $370 : local store [$359 <- $369]
      $371 = local load [ [$362[0]]]
      $372 = cast_value<f32> $371
      $373 : local store [$362 <- $372]
```
vs.
```
      $368 = alloca
      $369 = local load [ [$359[0]]]
      $370 = cast_value<f32> $369
      $371 : local store [$368 <- $370]
      $372 = alloca
      $373 = local load [ [$362[0]]]
      $374 = cast_value<f32> $373
      $375 : local store [$372 <- $374]
```
In first.txt, since $370 stores back to $359, the statement `$359 = alloca` cannot have both i32 and f32 types. In fact, $359 gets its i32 type here, where $3 must be storing `x` in the Python code:
```
      $359 = alloca
      $360 = local load [ [$3[0]]]
      $361 : local store [$359 <- $360]
```
See also: https://github.com/taichi-dev/taichi/blob/a54c9dfb3a0a3a7c26476b221ee434f17d72ec15/taichi/transforms/type_check.cpp#L29-L34

> ```python
> delta=0.001
> @ti.func
> def get_normal(x: int, y: int, z: float):
>     x = float(x)  # 1
>     y = float(y)  # 1
>     dx = sample_volume_trilinear(x + delta, y, z) - sample_volume_trilinear(x - delta, y, z)  # 2
>     dy = sample_volume_trilinear(x, y + delta, z) - sample_volume_trilinear(x, y - delta, z)  # 2
>     dz = sample_volume_trilinear(x, y, z + delta) - sample_volume_trilinear(x, y, z - delta)  # 2
>     n = ti.Vector([dx, dy, dz])
>     return n / n.norm()
> ```
> With that function, I got some runtime warnings, which basically state that on lines makred `1`, I tried to store float numbers in int variables, and on lines marked `2` I tried to convert implicitly convert ints to floats. But, that was not my intention. I, in a Pythonic lazy way, intended to make `x` and `y` hold float values. 

So this happens because `@tmp114 = (cast_value<f32> @tmp114)` is not SSA. I'm not sure if this can be fixed here:
https://github.com/taichi-dev/taichi/blob/a54c9dfb3a0a3a7c26476b221ee434f17d72ec15/taichi/transforms/lower_ast.cpp#L359-L363

The performance issue might need more investigation between second.txt and the IR generated from `def get_normal(x: float, y: float, z: float):`.

**Comment by ifsheldon** [comment] 2021-05-31 15:08
> The interesting bit is that normal wasn't get used anywhere, so Taichi aggressively optimized this kernel to a point where all the computations are eliminated. You can try writing normal back to some field. Basically we're trying to confirm if the slowness was indeed caused by the excessive casts.

Now I change it to 
```python
@ti.kernel
def simple_DVR():
    for x, y in pixels:
        idx_x = x // scaling
        idx_y = y // scaling
        max_marching_steps = int(slice_num / step_size)
        position = tl.vec3(idx_x, idx_y, 0.0)
        temp = tl.vec3(0.0)
        for step in range(max_marching_steps):
            # shading
            normal = get_normal(idx_x, idx_y, position.z)
            temp = normal

        pixels[x, y] = temp
```
then, it should not be optimized out, I think.
And the output ir are
[first.txt](https://github.com/taichi-dev/taichi/files/6571060/first.txt)
[second.txt](https://github.com/taichi-dev/taichi/files/6571063/second.txt)

The second version's ir roughly has 2k more lines than the first one.
Here is the code 
```python
import taichi as ti
import utils
import numpy as np
import taichi_glsl as tl

ti.init(arch=ti.cuda, print_ir=True)
data = utils.load_head_data()
data_f = (data / float(np.iinfo(np.uint16).max)).astype(np.float32)
width, height, slice_num = data.shape
scaling = 5
data_field = ti.field(ti.f32, shape=(width, height, slice_num))
pixels = ti.Vector.field(3, dtype=ti.f32, shape=(width * scaling, height * scaling))
data_field.from_numpy(data_f)
slice_num = int(slice_num)
step_size = 0.425
delta = step_size / 4.0


@ti.func
def low_high_frac(x: float):
    low = int(x)
    high = low + 1
    frac = x - low
    return low, high, frac


@ti.func
def sample_volume_trilinear(x: float, y: float, z: float):
    x_low, x_high, x_frac = low_high_frac(x)
    y_low, y_high, y_frac = low_high_frac(y)
    z_low, z_high, z_frac = low_high_frac(z)
    # on z_low
    v000 = data_field[x_low, y_low, z_low]
    v100 = data_field[x_high, y_low, z_low]
    x_val_y_low = tl.mix(v000, v100, x_frac)
    v010 = data_field[x_low, y_high, z_low]
    v110 = data_field[x_high, y_high, z_low]
    x_val_y_high = tl.mix(v010, v110, x_frac)
    xy_val_z_low = tl.mix(x_val_y_low, x_val_y_high, y_frac)
    # on z_high
    v001 = data_field[x_low, y_low, z_high]
    v101 = data_field[x_high, y_low, z_high]
    x_val_y_low = tl.mix(v001, v101, x_frac)
    v011 = data_field[x_low, y_high, z_high]
    v111 = data_field[x_high, y_high, z_high]
    x_val_y_high = tl.mix(v011, v111, x_frac)
    xy_val_z_high = tl.mix(x_val_y_low, x_val_y_high, y_frac)
    return tl.mix(xy_val_z_low, xy_val_z_high, z_frac)


# first version
@ti.func
def get_normal(x: int, y: int, z: float):
    x = float(x)
    y = float(y)
    dx = sample_volume_trilinear(x + delta, y, z) - sample_volume_trilinear(x - delta, y, z)
    dy = sample_volume_trilinear(x, y + delta, z) - sample_volume_trilinear(x, y - delta, z)
    dz = sample_volume_trilinear(x, y, z + delta) - sample_volume_trilinear(x, y, z - delta)
    n = ti.Vector([dx, dy, dz])
    return n.normalized()


# second version
# @ti.func
# def get_normal(x: int, y: int, z: float):
#     xf = float(x)
#     yf = float(y)
#     dx = sample_volume_trilinear(xf + delta, yf, z) - sample_volume_trilinear(xf - delta, yf, z)
#     dy = sample_volume_trilinear(xf, yf + delta, z) - sample_volume_trilinear(xf, yf - delta, z)
#     dz = sample_volume_trilinear(xf, yf, z + delta) - sample_volume_trilinear(xf, yf, z - delta)
#     n = ti.Vector([dx, dy, dz])
#     return n.normalized()


@ti.kernel
def simple_DVR():
    for x, y in pixels:
        idx_x = x // scaling
        idx_y = y // scaling
        max_marching_steps = int(slice_num / step_size)
        position = tl.vec3(idx_x, idx_y, 0.0)
        temp = tl.vec3(0.0)
        for step in range(max_marching_steps):
            normal = get_normal(idx_x, idx_y, position.z)
            temp = normal

        pixels[x, y] = temp


gui = ti.GUI("SciVis Slicing", res=(width * scaling, height * scaling), fast_gui=True)
while gui.running:
    simple_DVR()
    gui.set_image(pixels)
    gui.show()

```

**Comment by ifsheldon** [comment] 2021-05-31 15:17
> The performance issue might need more investigation between second.txt and the IR generated from def get_normal(x: float, y: float, z: float):.

But the performance degrade happened before I optimized `get_normal` to accept float values. In the first version and second version, both `get_normal` accept `(x: int, y: int, z: float)` as arguments and indeed parameters that were passed to `get_normal` have the corresponding types. The only differences are just lines marked with `1` and `2`.

**Comment by xumingkuan** [comment] 2021-06-01 09:21
FYI, I just found that `x = float(x)` (or `x = ti.cast(x, ti.f32)`) in Taichi causes "Local store may lose precision" no matter where this statement is written (in `@ti.func` or `@ti.kernel`, and `x` being an argument of the function or not), and this statement is transformed into `x = int(float(x))` which has no effect when the compilation config `fast_math=True` (by default). So the first version is equivalent to a version without the two lines marked with `1`:
```python
delta=0.001
@ti.func
def get_normal(x: int, y: int, z: float):
    # x = float(x)  # 1
    # y = float(y)  # 1
    dx = sample_volume_trilinear(x + delta, y, z) - sample_volume_trilinear(x - delta, y, z)  # 2
    dy = sample_volume_trilinear(x, y + delta, z) - sample_volume_trilinear(x, y - delta, z)  # 2
    dz = sample_volume_trilinear(x, y, z + delta) - sample_volume_trilinear(x, y, z - delta)  # 2
    n = ti.Vector([dx, dy, dz])
    return n / n.norm()
```

**Comment by xumingkuan** [comment] 2021-06-01 09:58
The performance issue comes from here I think:
```python

@ti.func
def low_high_frac(x: float):
    low = int(x)
    high = low + 1
    frac = x - low
    return low, high, frac


@ti.func
def sample_volume_trilinear(x: float, y: float, z: float):
    x_low, x_high, x_frac = low_high_frac(x)


# second version
@ti.func
def get_normal(x: int, y: int, z: float):
    xf = float(x)
    yf = float(y)
    dy = sample_volume_trilinear(xf, yf + delta, z) - sample_volume_trilinear(xf, yf - delta, z)
```

This produces the following IR:
```
[I 05/31/21 17:59:18.992] [compile_to_offloads.cpp:operator()@22] [simple_DVR_c32_0] Simplified I:
kernel {
  <f32> $0 = const [1.10625]
  <f32> $1 = const [0.89375]
  <f32> $2 = const [-0.10625]
  <f32> $3 = const [1.0]
  <i32> $4 = const [0]
  <i32> $5 = const [1]
  <f32> $6 = const [0.10625]
  <i32> $7 = const [400]
  <i32> $8 = const [5]
  $9 : struct for in S3dense (vectorize 1) (bit_vectorize -1) noneblock_dim=adaptive {
    <i32> $10 = loop $9 index 0
    <i32> $11 = loop $9 index 1
    <i32> $12 = floordiv $10 $8  // x
    <i32> $13 = floordiv $11 $8
    <f32> $14 = alloca
    <f32> $15 = alloca
    <f32> $16 = alloca
    <f32> $17 = cast_value<f32> $12  // xf = float(x), which is passed into low_high_frac
    <f32> $18 = cast_value<f32> $13
    <f32> $19 = add $17 $6
    <i32> $20 = cast_value<i32> $18
    <f32> $21 = sub $17 $6
    <f32> $22 = add $18 $6
    <i32> $23 = cast_value<i32> $17  // low = int(x)
    <f32> $24 = sub $18 $6
    <i32> $25 = cast_value<i32> $19
    <i32> $26 = add $20 $5
    <f32> $27 = cast_value<f32> $20
    <i32> $28 = cast_value<i32> $21
    <i32> $29 = add $23 $5
    <f32> $30 = cast_value<f32> $23  // x - low => x - float(low), because x is float type
    <i32> $31 = cast_value<i32> $22
    <i32> $32 = cast_value<i32> $24
    <i32> $33 = add $25 $5
    <f32> $34 = cast_value<f32> $25
    <f32> $35 = sub $18 $27
    <i32> $36 = add $28 $5
    <f32> $37 = cast_value<f32> $28
    <f32> $38 = sub $17 $30  // frac = x - float(low)
```
Our optimization pass is able to find that `frac` is 0 in the first version, but unable to find that `frac` is 0 (i.e., `$38 = f32($12) - f32(i32(f32($12))) = 0`) for now.

**Comment by xumingkuan** [comment] 2021-06-01 13:36
The performance issue should be fixed in the PR. Regarding the warnings about local store may lose precision, maybe we should add something to the document to clarify that code like this stores `float(x)` into the integer variable `x`?
```Python
x = 1
x = float(x)
```

**Comment by ifsheldon** [comment] 2021-06-01 22:02
> maybe we should add something to the document to clarify that code like this stores float(x) into the integer variable x?

Definitely! I think you should mention something like: even the code is embedded in Python, the variables in `ti.kernel` and `ti.func` behave not the same as conventional Python variable, in that they do have fixed data types somewhat like `auto var` in C++ unlike variable-type variables in Python.

**Comment by ifsheldon** [comment] 2021-06-01 22:34
The fix looks unusual at least for me because that means you have to peek into lower levels of function calls in order to optimize this. I mean in your test case in #2390, you have to look at lower 2 levels of function calls, but in theory, I can do many many levels of function calls. Something like the below maybe a trouble.
```python
@ti.func
def low_high_frac(x: float):
    low = int(x)
    high = low + 1
    frac = x - low
    return low, high, frac

@ti.func
def low_high_2frac(x: float):
    l, h, f = low_high_frac(x)
    return l, h, 2*f

def low_high_frac_exp(x:float):
    l, h, f = low_high_frac(x)
    return l, h, exp(f)

@ti.func
def sample(x: float):
    x_low, x_high, x_2frac = low_high_2frac(x)
    return x_2frac

@ti.func
def sample_exp(x: float):
    x_low, x_high, x_frac_exp = low_high_frac_exp(x)
    return x_frac_exp


@ti.kernel
def get_normal(x: int):
    xf = float(x)
    dy = sample(xf)
    dy1 = sample_exp(xf)
    print(dy)


get_normal(2)
```

**Comment by k-ye** [comment] 2021-06-02 01:46
>  I think you should mention something like: even the code is embedded in Python, the variables in ti.kernel and ti.func behave not the same as conventional Python variables, in that they do have fixed data types somewhat like auto var in C++ unlike variable-type variables in Python.

They are not: https://taichi.readthedocs.io/en/latest/hello.html#functions-and-kernels. But yeah the doc may need to further highlight the "statically-typed, lexically-scoped" part, and  provide a few examples.

>  And I suggest you provide an API for setting different levels of optimizations if you want to keep aggressive optimizations and at the mean time give tractable code for debugging and consistent performance expectation.

Good point

> The fix looks unusual at least for me because that means you have to peek into lower levels of function calls in order to optimize this.

The (un)fortunate thing is that Taichi inlines all its functions. So such kind of nested casts are propagated into the deepest @ti.func directly. I guess if these are actual function calls, they might just be of equal performance.

**Comment by xumingkuan** [comment] 2021-06-02 04:59
> The fix looks unusual at least for me because that means you have to peek into lower levels of function calls in order to optimize this. I mean in your test case in #2390, you have to look at lower 2 levels of function calls, but in theory, I can do many many levels of function calls. Something like the below maybe a trouble and I don't know if your fix can handle this.

Since Taichi inlines all its functions, my fix can handle this and the final IR is
```
  $0 = offloaded  
  body {
    <f32> $1 = const [0.0]
    <f32> $2 = const [1.0]
    print $1, "\n"
    print $2, "\n"  // print(dy1)
  }
```

> And I suggest you provide an API for setting different levels of optimizations if you want to keep aggressive optimizations and at the mean time give tractable code for debugging and consistent performance expectation.

Actually we already have a compile flag `advanced_optimization`. If I set `ti.init(print_ir=True, advanced_optimization=False)` in this test case, the resulting IR will be
```
  $0 = offloaded  
  body {
    <i32> $1 = arg[0]
    <f32> $2 = cast_value<f32> $1
    <i32> $3 = cast_value<i32> $2
    <f32> $4 = cast_value<f32> $3
    <f32> $5 = sub $2 $4
    <i32> $6 = const [2]
    <f32> $7 = cast_value<f32> $6
    <f32> $8 = mul $7 $5
    <i32> $9 = cast_value<i32> $2
    <f32> $10 = cast_value<f32> $9
    <f32> $11 = sub $2 $10
    <f32> $12 = exp $11
    print $8, "\n"
    print $12, "\n"
  }
```

Although I'm not sure if it would help, you can check if the first and second cases in this issue are both slow when `advanced_optimization=False`.

Nevertheless, I think we may need a more flexible API. The flag `advanced_optimization` looks like toggling `-O3` or `-O2` in `g++`, but we don't have an `-O0` flag for now. Maybe we should change the flag to something like `optimization_level`, and set `optimization_level=0` to something like disable all optimizations? (Note: Some optimization passes are necessary for some transform passes to work, e.g. DIE is necessary for lower_access. We may need to integrate DIE into lower_access in this case.)

**Closed** 2021-06-03 01:57 UTC
Labels: potential bug
