### ISSUE TITLE
Draw circles/particles with different radii in GGUI

### ISSUE THREAD

**Issue by YouJiacheng** [taichi-dev/taichi#6999] opened 2022-12-28 09:23 UTC
**Concisely describe the proposed feature**
Currently `canvas.circles` and `scene.particles` only supports a single scalar radius, prevent users drawing many circles/particles with different radii in batch. I would like to draw many circles/particles with different radii efficiently, using one `canvas.circles` or `scene.particles` call.

**Describe the solution you'd like (if any)**
Allow parameter `radius` to be a taichi field. 

**Additional comments**
`ti.GUI.circles` allows parameter `radius` to be a numpy ndarray. BTW, the documentation seems outdated:
https://github.com/taichi-dev/taichi/blob/449a7f60a57fd0e2213bc8fe984cd6627feef9ce/python/taichi/ui/gui.py#L355-L365

https://github.com/taichi-dev/taichi/blob/449a7f60a57fd0e2213bc8fe984cd6627feef9ce/python/taichi/ui/gui.py#L430-L434

It should be `radius (Union[Number, np.array], optional)` like `ti.GUI.arrows`.

**Comment by YouJiacheng** [comment] 2023-01-05 07:56
Hmmm. I don't think this issue should be closed by a docstring fix. 
1. Does the `canvas.circles` really support array `radius`? And I afraid it should be taichi field instead of numpy array in GGUI.
2. What about `scene.particles`?

**Comment by bobcao3** [comment] 2023-01-12 10:34
Duplicate of #3888 ?

**Closed** 2023-06-03 06:25 UTC
Labels: feature request
