### ISSUE TITLE
using ti.init(), the result is right, but using `ti.init(arch=ti.gpu)` , the result is wrong

### ISSUE THREAD

**Issue by l1t1** [taichi-dev/taichi#6113] opened 2022-09-20 06:14 UTC
**Describe the bug**
using ti.init(), the result is right, but using `ti.init(arch=ti.gpu)` , the result is wrong.

**To Reproduce**
following code is copied from your blog article(https://docs.taichi-lang.org/zh-Hans/blog/accelerate-python-code-100x)
```py
"""Count the number of primes below a given bound.
"""
import taichi as ti
ti.init()

@ti.func
def is_prime(n: int):
    result = True
    for k in range(2, int(n ** 0.5) + 1):
        if n % k == 0:
            result = False
            break
    return result

@ti.kernel
def count_primes(n: int) -> int:
    count = 0
    for k in range(2, n):
        if is_prime(k):
            count += 1

    return count

print(count_primes(1000000))
```
the result is `78498`.
if we modified the parameter of ti.init() to `arch=ti.gpu`, the result was `78513`

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
$ python my_sample_code.py
[Taichi] version 1.1.2, llvm 10.0.0, commit f25cf4a2, win, python 3.8.8
[Taichi] Starting on arch=cuda
...
```

**Additional comments**
If possible, please also consider attaching the output of command `ti diagnose`. This produces the detailed environment information and hopefully helps us diagnose faster.

If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.

**Comment by l1t1** [comment] 2022-09-20 06:16
the log of ti.init()
```
[Taichi] version 1.1.2, llvm 10.0.0, commit f25cf4a2, win, python 3.8.8
[Taichi] Starting on arch=x64
```

**Comment by l1t1** [comment] 2022-09-20 06:26
btw, using `ti.init(arch=ti.opengl)`, the result is wrong too.
```
[Taichi] version 1.1.2, llvm 10.0.0, commit f25cf4a2, win, python 3.8.8
[Taichi] Starting on arch=opengl
78513
```

**Comment by lin-hitonami** [comment] 2022-09-20 07:59
Can you attach the output of command `ti diagnose`? I can't reproduce this error using RTX3080, but I suspect that it may be because the precision of `n ** 0.5` on GPU is lower than the precision on CPU.

**Comment by l1t1** [comment] 2022-09-21 04:50
```
[Taichi] version 1.1.2, llvm 10.0.0, commit f25cf4a2, win, python 3.8.8

*******************************************
**      Taichi Programming Language      **
*******************************************

Docs:   https://docs.taichi-lang.org/
GitHub: https://github.com/taichi-dev/taichi/
Forum:  https://forum.taichi.graphics/

Taichi system diagnose:

python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
system: win32
executable: d:\python38\python.exe
platform: Windows-7-6.1.7601-SP1
architecture: 64bit WindowsPE
uname: uname_result(system='Windows', node='001-PC', release='7', version='6.1.7601', machine='AMD64', processor='Intel64 Family 6 Model 63 Stepping 2
, GenuineIntel')
locale: zh_CN.cp936
PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;C:\Windows\system3
2;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Calibre2\;C:\Program Files\Git\cmd;C:\Program Files
 (x86)\HP\IdrsOCR_15.2.10.1114\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SQL Server\120\To
ols\Binn\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.3.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\Python38\Scripts\;D:\
Python38\;E:\Docker_Toolbox;D:\Python38\Lib\site-packages\taichi\_lib
PYTHONPATH: ['D:\\Python38\\Scripts\\ti.exe', 'd:\\python38\\python38.zip', 'd:\\python38\\DLLs', 'd:\\python38\\lib', 'd:\\python38', 'd:\\python38\\
lib\\site-packages', 'd:\\python38\\lib\\site-packages\\win32', 'd:\\python38\\lib\\site-packages\\win32\\lib', 'd:\\python38\\lib\\site-packages\\Pyt
honwin']

`lsb_release` not available: [WinError 2] 系统找不到指定的文件。


import: <module 'taichi' from 'd:\\python38\\lib\\site-packages\\taichi\\__init__.py'>

cc: False
cpu: True
metal: False
opengl: True
cuda: True
vulkan: True

`glewinfo` not available: [WinError 2] 系统找不到指定的文件。

`nvidia-smi` not available: [WinError 2] 系统找不到指定的文件。
[Taichi] version 1.1.2, llvm 10.0.0, commit f25cf4a2, win, python 3.8.8

[Taichi] version 1.1.2, llvm 10.0.0, commit f25cf4a2, win, python 3.8.8
[Taichi] Starting on arch=x64

[Taichi] version 1.1.2, llvm 10.0.0, commit f25cf4a2, win, python 3.8.8
[Taichi] Starting on arch=opengl

[Taichi] version 1.1.2, llvm 10.0.0, commit f25cf4a2, win, python 3.8.8
[Taichi] Starting on arch=cuda

[Taichi] version 1.1.2, llvm 10.0.0, commit f25cf4a2, win, python 3.8.8

*******************************************
**      Taichi Programming Language      **
*******************************************

Docs:   https://docs.taichi-lang.org/
GitHub: https://github.com/taichi-dev/taichi/
Forum:  https://forum.taichi.graphics/

                                TAICHI EXAMPLES
+-----------------------------------------------------------------------------+
| 0: ad_gravity           | 22: keyboard             | 44: patterns           |
| 1: comet                | 23: laplace              | 45: pbf2d              |
| 2: cornell_box          | 24: mandelbrot_zoom      | 46: physarum           |
| 3: diff_sph             | 25: marching_squares     | 47: print_offset       |
| 4: euler                | 26: mass_spring_3d_ggui  | 48: rasterizer         |
| 5: explicit_activation  | 27: mass_spring_game     | 49: regression         |
| 6: export_mesh          | 28:                      | 50: sdf_renderer       |
|                         | mass_spring_game_ggui    |                        |
| 7: export_ply           | 29: mciso_advanced       | 51: simple_derivative  |
| 8: export_videos        | 30: mgpcg                | 52: simple_texture     |
| 9: fem128               | 31: mgpcg_advanced       | 53: simple_uv          |
| 10: fem128_ggui         | 32: minimal              | 54: stable_fluid       |
| 11: fem99               | 33: minimization         | 55: stable_fluid_ggui  |
| 12: fractal             | 34: mpm128               | 56: stable_fluid_graph |
| 13: fractal3d_ggui      | 35: mpm128_ggui          | 57: taichi_bitmasked   |
| 14: fullscreen          | 36: mpm3d                | 58: taichi_dynamic     |
| 15: game_of_life        | 37: mpm3d_ggui           | 59: taichi_logo        |
| 16: gui_image_io        | 38: mpm88                | 60: taichi_sparse      |
| 17: gui_widgets         | 39: mpm88_graph          | 61: texture_graph      |
| 18: implicit_fem        | 40: mpm99                | 62: tutorial           |
| 19:                     | 41:                      | 63: vortex_rings       |
| implicit_mass_spring    | mpm_lagrangian_forces    |                        |
| 20:                     | 42: nbody                | 64: waterwave          |
| initial_value_problem   |                          |                        |
| 21: jacobian            | 43: odop_solar           |                        |
+-----------------------------------------------------------------------------+
Running example minimal ...
[Taichi] Starting on arch=x64
42.0
>>> Running time: 0.53s
42

Consider attaching this log when maintainers ask about system information.
>>> Running time: 23.32s
```

**Comment by l1t1** [comment] 2022-09-21 05:24
I tried to compare the result of is_prime() funtions, it failed.
```python
"""Count the number of primes below a given bound.
"""

def is_prime1(n: int):
    result = True
    for k in range(2, int(n ** 0.5) + 1):
        if n % k == 0:
            result = False
            break
    return result


def count_primes1(n: int) -> int:
    count = 0
    for k in range(2, n):
        if is_prime1(k):
            count += 1
    return count

print(count_primes1(1000000))

import taichi as ti
ti.init(arch=ti.gpu)
@ti.func
def is_prime(n: int):
    result = True
    for k in range(2, int(n ** 0.5) + 1):
        if n % k == 0:
            result = False
            break
    return result

@ti.kernel
def count_primes(n: int) -> int:
    count = 0
    for k in range(2, n):
        if is_prime(k)!=is_prime1(k):
            count += 1;print(k)
    return count

print(count_primes(1000000))
```
reports
```
D:\>python ex2gc.py
78498
[Taichi] version 1.1.2, llvm 10.0.0, commit f25cf4a2, win, python 3.8.8
[Taichi] Starting on arch=cuda
Traceback (most recent call last):
  File "ex2gc.py", line 41, in <module>
    print(count_primes(1000000))
  File "D:\Python38\lib\site-packages\taichi\lang\kernel_impl.py", line 920, in wrapped
    raise type(e)('\n' + str(e)) from None
taichi.lang.exception.TaichiCompilationError:
On line 37 of file "ex2gc.py", in count_primes:
        if is_prime(k)!=is_prime1(k):
                        ^^^^^^^^^^^^
Traceback (most recent call last):
  File "D:\Python38\lib\site-packages\taichi\lang\ast\ast_transformer_utils.py", line 24, in __call__
    return method(ctx, node)
  File "D:\Python38\lib\site-packages\taichi\lang\ast\ast_transformer.py", line 497, in build_Call
    node.ptr = func(*args, **keywords)
  File "ex2gc.py", line 6, in is_prime1
    for k in range(2, int(n ** 0.5) + 1):
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Expr'
```

**Comment by lin-hitonami** [comment] 2022-09-21 05:54
`count_primes1` is not a Taichi function (not decorated by `@ti.func`) so it cannot be used inside a Taichi kernel.

**Comment by turbo0628** [comment] 2022-09-21 14:40
I can neither reproduce the same error. What GPU are you using?

**Comment by l1t1** [comment] 2022-09-22 00:27
Quadro K5200
```
D:\>"C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe"
Thu Sep 22 08:21:45 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 425.25       Driver Version: 425.25       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro K5200       WDDM  | 00000000:81:00.0  On |                  Off |
| 46%   78C    P0   120W / 150W |   2147MiB /  8192MiB |     95%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      5132    C+G   C:\Windows\Explorer.EXE                    N/A      |
```

**Comment by l1t1** [comment] 2022-09-22 09:14
`ti.init(arch=ti.cuda, default_fp=ti.f64)` fixed the problem. thanks
```
[Taichi] version 1.1.2, llvm 10.0.0, commit f25cf4a2, win, python 3.8.8
[Taichi] Starting on arch=cuda
78498
```
@turbo0628

**Comment by turbo0628** [comment] 2022-09-23 05:45
Great!

Then it's an FP32 precision problem for the legacy Kepler architecture.

As this architecture is no longer supported by vendor, I'm going to close this issue.

Feel free to reopen when you have further questions.

**Closed by turbo0628** 2022-09-23 05:45 UTC
Labels: potential bug
