### ISSUE TITLE
`libtaichi_core.so` cannot be automatically removed by `pip uninstall` on macos

### ISSUE THREAD

**Issue by ljcc0930** [taichi-dev/taichi#2790] opened 2021-08-24 05:53 UTC
Installed by the same procedure in issue #2787.
```sh
github@shui ~ % python3 -m pip uninstall taichi
Found existing installation: taichi 0.7.29
Uninstalling taichi-0.7.29:
  Would remove:
    /Users/github/Library/Python/3.8/bin/ti
    /Users/github/Library/Python/3.8/lib/python/site-packages/taichi-0.7.29.dist-info/*
    /Users/github/Library/Python/3.8/lib/python/site-packages/taichi/*
  Would not remove (might be manually added):
    /Users/github/Library/Python/3.8/lib/python/site-packages/taichi/lib/libtaichi_core.so
Proceed (Y/n)? n
```

**Comment by gaocegege** [comment] 2021-09-10 10:46
Cannot reproduce it if the `site-packages/taichi/` does not exist before installing the whl. 

Maybe you can delete the directory /Users/github/Library/Python/3.8/lib/python/site-packages/taichi/ manually then have another try.

Maybe the directory is polluted by previous installation using `setuptools`.

**Comment by frostming** [comment] 2022-03-04 08:26
Closing since it can't be reproduced using the latest version.

**Closed by frostming** 2022-03-04 08:26 UTC
Labels: welcome contribution, potential bug
